/// <reference types="node" />
export declare class NativeRenderer {
  constructor()
  render(scene: RenderScene, camera: Camera): Buffer
}

export interface Camera {
  /** Output width in pixels. */
  width?: number
  /** Output height in pixels. */
  height?: number
  /** Camera position. Defaults to `[2.5, 1.8, 3.2]`. */
  eye?: Array<number>
  /** Look-at target. Defaults to `[0, 0, 0]`. */
  target?: Array<number>
  /** Up direction. Defaults to `[0, 1, 0]`. */
  up?: Array<number>
  /** Vertical field of view in degrees. Defaults to `45`. */
  fovYDegrees?: number
  /** Near clipping plane. Defaults to `0.01`. */
  near?: number
  /** Far clipping plane. Defaults to `100`. */
  far?: number
  /** Optional column-major 4x4 view-projection matrix in WebGPU clip space. */
  viewProjection?: Array<number>
}

export declare function renderNative(scene: RenderScene, camera: Camera): Buffer

export interface RenderScene {
  /** Output width in pixels. `camera.width` takes precedence when set. */
  width?: number
  /** Output height in pixels. `camera.height` takes precedence when set. */
  height?: number
  /** Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range. */
  background?: Array<number>
  /** Output format. Supported values are `"png"` (default) and `"rgba"`. */
  format?: string
  /** Triangle-list meshes generated by the JavaScript Three.js adapter. */
  meshes?: Array<SceneMesh>
}

export interface SceneMesh {
  /** Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`. */
  positions: Array<number>
  /** Optional uint32 triangle-list indices. */
  indices?: Array<number>
  /** Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex. */
  colors?: Array<number>
  /** Mesh material color used when `colors` is omitted. */
  color?: Array<number>
  /** Optional column-major 4x4 model matrix. */
  transform?: Array<number>
}
