/// <reference types="node" />
export declare class NativeRenderer {
  constructor()
  render(scene: RenderScene, camera: Camera): Buffer
}

export interface Camera {
  /** Output width in pixels. */
  width?: number
  /** Output height in pixels. */
  height?: number
  /** Camera position. Defaults to `[2.5, 1.8, 3.2]`. */
  eye?: Array<number>
  /** Look-at target. Defaults to `[0, 0, 0]`. */
  target?: Array<number>
  /** Up direction. Defaults to `[0, 1, 0]`. */
  up?: Array<number>
  /** Vertical field of view in degrees. Defaults to `45`. */
  fovYDegrees?: number
  /** Near clipping plane. Defaults to `0.01`. */
  near?: number
  /** Far clipping plane. Defaults to `100`. */
  far?: number
  /** Optional column-major 4x4 view-projection matrix in WebGPU clip space. */
  viewProjection?: Array<number>
  /** Camera world position `[x, y, z]` for PBR lighting. */
  cameraPosition?: Array<number>
}

export declare function renderNative(scene: RenderScene, camera: Camera): Buffer

export interface RenderScene {
  /** Output width in pixels. `camera.width` takes precedence when set. */
  width?: number
  /** Output height in pixels. `camera.height` takes precedence when set. */
  height?: number
  /** Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range. */
  background?: Array<number>
  /** Output format. Supported values are `"png"` (default) and `"rgba"`. */
  format?: string
  /** Triangle-list meshes generated by the JavaScript Three.js adapter. */
  meshes?: Array<SceneMesh>
  /** Scene lights. */
  lights?: Array<SceneLight>
  /** Ambient light color `[r, g, b]` in 0..1 range. */
  ambientLight?: Array<number>
  /** Ambient light intensity. Defaults to 0. */
  ambientIntensity?: number
}

export interface SceneLight {
  /** Light type: `"directional"`, `"point"`, or `"spot"`. */
  lightType: string
  /** Light color `[r, g, b]` in 0..1 range. */
  color?: Array<number>
  /** Light intensity. */
  intensity?: number
  /** World-space position `[x, y, z]` (point and spot lights). */
  position?: Array<number>
  /** Direction `[x, y, z]` (directional and spot lights). */
  direction?: Array<number>
}

export interface SceneMesh {
  /** Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`. */
  positions: Array<number>
  /** Optional uint32 triangle-list indices. */
  indices?: Array<number>
  /** Optional per-vertex normals: `[nx0, ny0, nz0, ...]`. */
  normals?: Array<number>
  /** Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex. */
  colors?: Array<number>
  /** Mesh material color used when `colors` is omitted. */
  color?: Array<number>
  /** Optional column-major 4x4 model matrix. */
  transform?: Array<number>
  /** Optional per-vertex UV coordinates: `[u0, v0, u1, v1, ...]`. */
  uvs?: Array<number>
  /** Optional texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP). */
  texture?: Buffer
  /** Texture width in pixels (required when `texture` is raw RGBA8 bytes). */
  textureWidth?: number
  /** Texture height in pixels (required when `texture` is raw RGBA8 bytes). */
  textureHeight?: number
  /** Metallic factor (0..1). Defaults to 0. */
  metallic?: number
  /** Roughness factor (0..1). Defaults to 1. */
  roughness?: number
  /** Emissive color `[r, g, b]` in 0..1 range. */
  emissive?: Array<number>
  /** Emissive intensity multiplier. Defaults to 1. */
  emissiveIntensity?: number
}
