use napi::bindgen_prelude::Buffer;
use napi_derive::napi;

#[napi(object)]
#[derive(Default)]
pub struct RenderScene {
    /// Output width in pixels. `camera.width` takes precedence when set.
    pub width: Option<u32>,
    /// Output height in pixels. `camera.height` takes precedence when set.
    pub height: Option<u32>,
    /// Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range.
    pub background: Option<Vec<f64>>,
    /// Background color/texture intensity multiplier. Defaults to 1.
    pub background_intensity: Option<f64>,
    /// Optional output viewport `[x, y, width, height]` in top-left pixel coordinates.
    pub viewport: Option<Vec<f64>>,
    /// Optional output scissor rectangle `[x, y, width, height]` in top-left pixel coordinates.
    pub scissor: Option<Vec<f64>>,
    /// Optional scene background texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub background_texture: Option<Buffer>,
    /// Background texture width in pixels (required when `background_texture` is raw RGBA8 bytes).
    pub background_texture_width: Option<u32>,
    /// Background texture height in pixels (required when `background_texture` is raw RGBA8 bytes).
    pub background_texture_height: Option<u32>,
    /// Background texture horizontal wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub background_texture_wrap_s: Option<String>,
    /// Background texture vertical wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub background_texture_wrap_t: Option<String>,
    /// Background texture magnification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub background_texture_mag_filter: Option<String>,
    /// Background texture minification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub background_texture_min_filter: Option<String>,
    /// Background texture UV transform `[a, c, tx, b, d, ty]`.
    pub background_texture_transform: Option<Vec<f64>>,
    /// Background texture color space. `"srgb"` is decoded to linear before output conversion.
    pub background_texture_color_space: Option<String>,
    /// Approximate 2D background texture blur amount in the 0..1 range.
    pub background_texture_blurriness: Option<f64>,
    /// Output format. Supported values are `"png"` (default) and `"rgba"`.
    pub format: Option<String>,
    /// Output color space. Supported values are `"srgb"` (default) and `"srgb-linear"`.
    pub output_color_space: Option<String>,
    /// Triangle-list meshes generated by the JavaScript Three.js adapter.
    pub meshes: Option<Vec<SceneMesh>>,
    /// Scene lights.
    pub lights: Option<Vec<SceneLight>>,
    /// Ambient light color `[r, g, b]` in 0..1 range.
    pub ambient_light: Option<Vec<f64>>,
    /// Ambient light intensity. Defaults to 0.
    pub ambient_intensity: Option<f64>,
    /// Flattened LightProbe spherical-harmonics coefficients: 9 RGB triplets.
    pub light_probe: Option<Vec<f64>>,
    /// Optional environment map image data (equirectangular HDR/LDR, encoded or raw RGBA/Float).
    pub environment_map: Option<Buffer>,
    /// Environment map width in pixels (required when data is raw typed-array bytes).
    pub environment_map_width: Option<u32>,
    /// Environment map height in pixels (required when data is raw typed-array bytes).
    pub environment_map_height: Option<u32>,
    /// Environment map intensity multiplier. Defaults to 1.
    pub environment_map_intensity: Option<f64>,
    /// Scene fog mode: `"linear"` for THREE.Fog or `"exp2"` for THREE.FogExp2.
    pub fog_type: Option<String>,
    /// Fog color `[r, g, b]` in 0..1 range.
    pub fog_color: Option<Vec<f64>>,
    /// Linear fog near distance. Defaults to 1.
    pub fog_near: Option<f64>,
    /// Linear fog far distance. Defaults to 1000.
    pub fog_far: Option<f64>,
    /// Exponential squared fog density. Defaults to 0.00025.
    pub fog_density: Option<f64>,
    /// Post-processing exposure adjustment in stops. Defaults to 0.
    pub post_exposure: Option<f64>,
    /// Post-processing contrast multiplier. Defaults to 1.
    pub post_contrast: Option<f64>,
    /// Post-processing saturation multiplier. Defaults to 1.
    pub post_saturation: Option<f64>,
    /// Post-processing vignette amount 0..1. Defaults to 0.
    pub post_vignette: Option<f64>,
    /// Post-processing grayscale blend 0..1. Defaults to 0.
    pub post_grayscale: Option<f64>,
    /// Post-processing inversion blend 0..1. Defaults to 0.
    pub post_invert: Option<f64>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneLight {
    /// Light type: `"directional"`, `"point"`, `"spot"`, `"rectArea"`, or `"hemisphere"`.
    pub light_type: String,
    /// Light color `[r, g, b]` in 0..1 range.
    pub color: Option<Vec<f64>>,
    /// Light intensity.
    pub intensity: Option<f64>,
    /// World-space position `[x, y, z]` (point and spot lights).
    pub position: Option<Vec<f64>>,
    /// Direction `[x, y, z]` (directional and spot lights, up for hemisphere).
    pub direction: Option<Vec<f64>>,
    /// Maximum range. 0 = infinite (point and spot).
    pub distance: Option<f64>,
    /// Decay exponent for distance falloff (point and spot). Defaults to 2.
    pub decay: Option<f64>,
    /// Spotlight half-angle in radians. Defaults to π/3.
    pub angle: Option<f64>,
    /// Spotlight penumbra 0..1. Defaults to 0.
    pub penumbra: Option<f64>,
    /// RectAreaLight width in world units.
    pub width: Option<f64>,
    /// RectAreaLight height in world units.
    pub height: Option<f64>,
    /// Hemisphere light ground color `[r, g, b]` in 0..1 range.
    pub ground_color: Option<Vec<f64>>,
    /// Whether this light casts shadows (directional, spot, and point lights).
    pub cast_shadow: Option<bool>,
    /// Shadow map resolution (square, pixels). Defaults to 512.
    pub shadow_map_size: Option<u32>,
    /// Depth bias in shadow-map NDC.
    pub shadow_bias: Option<f64>,
    /// Normal-offset bias in world space at the receiver.
    pub shadow_normal_bias: Option<f64>,
    /// Orthographic shadow-camera frustum bounds.
    pub shadow_camera_left: Option<f64>,
    pub shadow_camera_right: Option<f64>,
    pub shadow_camera_top: Option<f64>,
    pub shadow_camera_bottom: Option<f64>,
    pub shadow_camera_near: Option<f64>,
    pub shadow_camera_far: Option<f64>,
    /// Cascaded shadow split distances from the active camera.
    pub shadow_cascade_splits: Option<Vec<f64>>,
    /// Flattened cascade bounds: `[left, right, top, bottom, near, far, ...]`.
    pub shadow_cascade_bounds: Option<Vec<f64>>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneMesh {
    /// Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`.
    pub positions: Vec<f64>,
    /// Optional uint32 triangle-list indices.
    pub indices: Option<Vec<u32>>,
    /// Optional per-vertex normals: `[nx0, ny0, nz0, ...]`.
    pub normals: Option<Vec<f64>>,
    /// Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex.
    pub colors: Option<Vec<f64>>,
    /// Mesh material color used when `colors` is omitted.
    pub color: Option<Vec<f64>>,
    /// Optional column-major 4x4 model matrix.
    pub transform: Option<Vec<f64>>,
    /// Optional per-vertex UV coordinates: `[u0, v0, u1, v1, ...]`.
    pub uvs: Option<Vec<f64>>,
    /// Optional secondary UV coordinates, used by AO/light-style maps.
    pub uvs2: Option<Vec<f64>>,
    /// Use per-face normals for flat-shaded triangle materials.
    pub flat_shading: Option<bool>,
    /// Whether this material is affected by scene fog. Defaults to true.
    pub fog: Option<bool>,
    /// Optional texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub texture: Option<Buffer>,
    /// Texture width in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_width: Option<u32>,
    /// Texture height in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_height: Option<u32>,
    /// Texture horizontal wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub texture_wrap_s: Option<String>,
    /// Texture vertical wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub texture_wrap_t: Option<String>,
    /// Texture magnification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub texture_mag_filter: Option<String>,
    /// Texture minification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub texture_min_filter: Option<String>,
    /// Base-color map UV transform `[a, c, tx, b, d, ty]`.
    pub texture_transform: Option<Vec<f64>>,
    /// Base-color texture color space. `"srgb"` is decoded to linear before shading.
    pub texture_color_space: Option<String>,
    /// Whether base-color map sampling uses the secondary UV stream.
    pub texture_uses_uv2: Option<bool>,
    /// Optional metallic-roughness texture (glTF convention: G=roughness, B=metallic).
    pub metallic_roughness_texture: Option<Buffer>,
    /// Metallic-roughness texture width (required when texture is raw RGBA8 bytes).
    pub metallic_roughness_texture_width: Option<u32>,
    /// Metallic-roughness texture height (required when texture is raw RGBA8 bytes).
    pub metallic_roughness_texture_height: Option<u32>,
    /// Metallic-roughness texture horizontal wrap mode.
    pub metallic_roughness_texture_wrap_s: Option<String>,
    /// Metallic-roughness texture vertical wrap mode.
    pub metallic_roughness_texture_wrap_t: Option<String>,
    /// Metallic-roughness texture magnification filter.
    pub metallic_roughness_texture_mag_filter: Option<String>,
    /// Metallic-roughness texture minification filter.
    pub metallic_roughness_texture_min_filter: Option<String>,
    /// Metallic-roughness map UV transform `[a, c, tx, b, d, ty]`.
    pub metallic_roughness_texture_transform: Option<Vec<f64>>,
    /// Whether metallic-roughness map sampling uses the secondary UV stream.
    pub metallic_roughness_texture_uses_uv2: Option<bool>,
    /// Optional specular strength map. Red channel multiplies MeshPhongMaterial specular.
    pub specular_map: Option<Buffer>,
    /// Specular map width (required when map is raw RGBA8 bytes).
    pub specular_map_width: Option<u32>,
    /// Specular map height (required when map is raw RGBA8 bytes).
    pub specular_map_height: Option<u32>,
    /// Specular map horizontal wrap mode.
    pub specular_map_wrap_s: Option<String>,
    /// Specular map vertical wrap mode.
    pub specular_map_wrap_t: Option<String>,
    /// Specular map magnification filter.
    pub specular_map_mag_filter: Option<String>,
    /// Specular map minification filter.
    pub specular_map_min_filter: Option<String>,
    /// Specular map UV transform `[a, c, tx, b, d, ty]`.
    pub specular_map_transform: Option<Vec<f64>>,
    /// Metallic factor (0..1). Defaults to 0.
    pub metallic: Option<f64>,
    /// Roughness factor (0..1). Defaults to 1.
    pub roughness: Option<f64>,
    /// Clearcoat intensity (0..1) for MeshPhysicalMaterial. Defaults to 0.
    pub clearcoat: Option<f64>,
    /// Optional clearcoat intensity map. Red channel multiplies `clearcoat`.
    pub clearcoat_map: Option<Buffer>,
    /// Clearcoat map width (required when map is raw RGBA8 bytes).
    pub clearcoat_map_width: Option<u32>,
    /// Clearcoat map height (required when map is raw RGBA8 bytes).
    pub clearcoat_map_height: Option<u32>,
    /// Clearcoat map horizontal wrap mode.
    pub clearcoat_map_wrap_s: Option<String>,
    /// Clearcoat map vertical wrap mode.
    pub clearcoat_map_wrap_t: Option<String>,
    /// Clearcoat map magnification filter.
    pub clearcoat_map_mag_filter: Option<String>,
    /// Clearcoat map minification filter.
    pub clearcoat_map_min_filter: Option<String>,
    /// Clearcoat map UV transform `[a, c, tx, b, d, ty]`.
    pub clearcoat_map_transform: Option<Vec<f64>>,
    /// Whether clearcoat map sampling uses the secondary UV stream.
    pub clearcoat_map_uses_uv2: Option<bool>,
    /// Clearcoat roughness (0..1). Defaults to 0.
    pub clearcoat_roughness: Option<f64>,
    /// Optional clearcoat roughness map. Green channel multiplies `clearcoatRoughness`.
    pub clearcoat_roughness_map: Option<Buffer>,
    /// Clearcoat roughness map width (required when map is raw RGBA8 bytes).
    pub clearcoat_roughness_map_width: Option<u32>,
    /// Clearcoat roughness map height (required when map is raw RGBA8 bytes).
    pub clearcoat_roughness_map_height: Option<u32>,
    /// Clearcoat roughness map horizontal wrap mode.
    pub clearcoat_roughness_map_wrap_s: Option<String>,
    /// Clearcoat roughness map vertical wrap mode.
    pub clearcoat_roughness_map_wrap_t: Option<String>,
    /// Clearcoat roughness map magnification filter.
    pub clearcoat_roughness_map_mag_filter: Option<String>,
    /// Clearcoat roughness map minification filter.
    pub clearcoat_roughness_map_min_filter: Option<String>,
    /// Clearcoat roughness map UV transform `[a, c, tx, b, d, ty]`.
    pub clearcoat_roughness_map_transform: Option<Vec<f64>>,
    /// Whether clearcoat roughness map sampling uses the secondary UV stream.
    pub clearcoat_roughness_map_uses_uv2: Option<bool>,
    /// Optional clearcoat normal map.
    pub clearcoat_normal_map: Option<Buffer>,
    /// Clearcoat normal map width (required when map is raw RGBA8 bytes).
    pub clearcoat_normal_map_width: Option<u32>,
    /// Clearcoat normal map height (required when map is raw RGBA8 bytes).
    pub clearcoat_normal_map_height: Option<u32>,
    /// Clearcoat normal map horizontal wrap mode.
    pub clearcoat_normal_map_wrap_s: Option<String>,
    /// Clearcoat normal map vertical wrap mode.
    pub clearcoat_normal_map_wrap_t: Option<String>,
    /// Clearcoat normal map magnification filter.
    pub clearcoat_normal_map_mag_filter: Option<String>,
    /// Clearcoat normal map minification filter.
    pub clearcoat_normal_map_min_filter: Option<String>,
    /// Clearcoat normal map UV transform `[a, c, tx, b, d, ty]`.
    pub clearcoat_normal_map_transform: Option<Vec<f64>>,
    /// Whether clearcoat normal map sampling uses the secondary UV stream.
    pub clearcoat_normal_map_uses_uv2: Option<bool>,
    /// Clearcoat normal map scale `[x, y]`. Defaults to `[1, 1]`.
    pub clearcoat_normal_scale: Option<Vec<f64>>,
    /// Sheen color/intensity `[r, g, b]` in 0..1 range.
    pub sheen_color: Option<Vec<f64>>,
    /// Optional sheen color map. RGB channels multiply `sheenColor`.
    pub sheen_color_map: Option<Buffer>,
    /// Sheen color map width (required when map is raw RGBA8 bytes).
    pub sheen_color_map_width: Option<u32>,
    /// Sheen color map height (required when map is raw RGBA8 bytes).
    pub sheen_color_map_height: Option<u32>,
    /// Sheen color map horizontal wrap mode.
    pub sheen_color_map_wrap_s: Option<String>,
    /// Sheen color map vertical wrap mode.
    pub sheen_color_map_wrap_t: Option<String>,
    /// Sheen color map magnification filter.
    pub sheen_color_map_mag_filter: Option<String>,
    /// Sheen color map minification filter.
    pub sheen_color_map_min_filter: Option<String>,
    /// Sheen color map UV transform `[a, c, tx, b, d, ty]`.
    pub sheen_color_map_transform: Option<Vec<f64>>,
    /// Sheen color texture color space. `"srgb"` is decoded to linear before shading.
    pub sheen_color_map_color_space: Option<String>,
    /// Whether sheen color map sampling uses the secondary UV stream.
    pub sheen_color_map_uses_uv2: Option<bool>,
    /// Sheen roughness (0..1). Defaults to 1 when sheen is present.
    pub sheen_roughness: Option<f64>,
    /// Optional sheen roughness map. Alpha channel multiplies `sheenRoughness`.
    pub sheen_roughness_map: Option<Buffer>,
    /// Sheen roughness map width (required when map is raw RGBA8 bytes).
    pub sheen_roughness_map_width: Option<u32>,
    /// Sheen roughness map height (required when map is raw RGBA8 bytes).
    pub sheen_roughness_map_height: Option<u32>,
    /// Sheen roughness map horizontal wrap mode.
    pub sheen_roughness_map_wrap_s: Option<String>,
    /// Sheen roughness map vertical wrap mode.
    pub sheen_roughness_map_wrap_t: Option<String>,
    /// Sheen roughness map magnification filter.
    pub sheen_roughness_map_mag_filter: Option<String>,
    /// Sheen roughness map minification filter.
    pub sheen_roughness_map_min_filter: Option<String>,
    /// Sheen roughness map UV transform `[a, c, tx, b, d, ty]`.
    pub sheen_roughness_map_transform: Option<Vec<f64>>,
    /// Whether sheen roughness map sampling uses the secondary UV stream.
    pub sheen_roughness_map_uses_uv2: Option<bool>,
    /// Anisotropy strength (0..1). Defaults to 0.
    pub anisotropy: Option<f64>,
    /// Anisotropy rotation in tangent space, radians.
    pub anisotropy_rotation: Option<f64>,
    /// Optional anisotropy map. RG encode direction and B encodes strength.
    pub anisotropy_map: Option<Buffer>,
    /// Anisotropy map width (required when map is raw RGBA8 bytes).
    pub anisotropy_map_width: Option<u32>,
    /// Anisotropy map height (required when map is raw RGBA8 bytes).
    pub anisotropy_map_height: Option<u32>,
    /// Anisotropy map horizontal wrap mode.
    pub anisotropy_map_wrap_s: Option<String>,
    /// Anisotropy map vertical wrap mode.
    pub anisotropy_map_wrap_t: Option<String>,
    /// Anisotropy map magnification filter.
    pub anisotropy_map_mag_filter: Option<String>,
    /// Anisotropy map minification filter.
    pub anisotropy_map_min_filter: Option<String>,
    /// Anisotropy map UV transform `[a, c, tx, b, d, ty]`.
    pub anisotropy_map_transform: Option<Vec<f64>>,
    /// Whether anisotropy map sampling uses the secondary UV stream.
    pub anisotropy_map_uses_uv2: Option<bool>,
    /// Physical transmission factor (0..1). Defaults to 0.
    pub transmission: Option<f64>,
    /// Optional transmission map. Red channel multiplies `transmission`.
    pub transmission_map: Option<Buffer>,
    /// Transmission map width (required when map is raw RGBA8 bytes).
    pub transmission_map_width: Option<u32>,
    /// Transmission map height (required when map is raw RGBA8 bytes).
    pub transmission_map_height: Option<u32>,
    /// Transmission map horizontal wrap mode.
    pub transmission_map_wrap_s: Option<String>,
    /// Transmission map vertical wrap mode.
    pub transmission_map_wrap_t: Option<String>,
    /// Transmission map magnification filter.
    pub transmission_map_mag_filter: Option<String>,
    /// Transmission map minification filter.
    pub transmission_map_min_filter: Option<String>,
    /// Transmission map UV transform `[a, c, tx, b, d, ty]`.
    pub transmission_map_transform: Option<Vec<f64>>,
    /// Whether transmission map sampling uses the secondary UV stream.
    pub transmission_map_uses_uv2: Option<bool>,
    /// Index of refraction for physical materials. Defaults to 1.5.
    pub ior: Option<f64>,
    /// Transmission volume thickness in model units. Defaults to 0.
    pub thickness: Option<f64>,
    /// Optional thickness map. Green channel multiplies `thickness`.
    pub thickness_map: Option<Buffer>,
    /// Thickness map width (required when map is raw RGBA8 bytes).
    pub thickness_map_width: Option<u32>,
    /// Thickness map height (required when map is raw RGBA8 bytes).
    pub thickness_map_height: Option<u32>,
    /// Thickness map horizontal wrap mode.
    pub thickness_map_wrap_s: Option<String>,
    /// Thickness map vertical wrap mode.
    pub thickness_map_wrap_t: Option<String>,
    /// Thickness map magnification filter.
    pub thickness_map_mag_filter: Option<String>,
    /// Thickness map minification filter.
    pub thickness_map_min_filter: Option<String>,
    /// Thickness map UV transform `[a, c, tx, b, d, ty]`.
    pub thickness_map_transform: Option<Vec<f64>>,
    /// Whether thickness map sampling uses the secondary UV stream.
    pub thickness_map_uses_uv2: Option<bool>,
    /// Transmission attenuation distance. Defaults to a very large distance.
    pub attenuation_distance: Option<f64>,
    /// Transmission attenuation color `[r, g, b]` in 0..1 range.
    pub attenuation_color: Option<Vec<f64>>,
    /// MeshPhysicalMaterial specular color factor `[r, g, b]` in 0..1 range.
    pub physical_specular_color: Option<Vec<f64>>,
    /// MeshPhysicalMaterial specular intensity factor (0..1). Defaults to 1.
    pub physical_specular_intensity: Option<f64>,
    /// Optional MeshPhysicalMaterial specular color map. RGB channels multiply `specularColor`.
    pub specular_color_map: Option<Buffer>,
    /// Specular color map width (required when map is raw RGBA8 bytes).
    pub specular_color_map_width: Option<u32>,
    /// Specular color map height (required when map is raw RGBA8 bytes).
    pub specular_color_map_height: Option<u32>,
    /// Specular color map horizontal wrap mode.
    pub specular_color_map_wrap_s: Option<String>,
    /// Specular color map vertical wrap mode.
    pub specular_color_map_wrap_t: Option<String>,
    /// Specular color map magnification filter.
    pub specular_color_map_mag_filter: Option<String>,
    /// Specular color map minification filter.
    pub specular_color_map_min_filter: Option<String>,
    /// Specular color map UV transform `[a, c, tx, b, d, ty]`.
    pub specular_color_map_transform: Option<Vec<f64>>,
    /// Specular color texture color space. `"srgb"` is decoded to linear before shading.
    pub specular_color_map_color_space: Option<String>,
    /// Whether specular color map sampling uses the secondary UV stream.
    pub specular_color_map_uses_uv2: Option<bool>,
    /// Optional MeshPhysicalMaterial specular intensity map. Alpha channel multiplies `specularIntensity`.
    pub specular_intensity_map: Option<Buffer>,
    /// Specular intensity map width (required when map is raw RGBA8 bytes).
    pub specular_intensity_map_width: Option<u32>,
    /// Specular intensity map height (required when map is raw RGBA8 bytes).
    pub specular_intensity_map_height: Option<u32>,
    /// Specular intensity map horizontal wrap mode.
    pub specular_intensity_map_wrap_s: Option<String>,
    /// Specular intensity map vertical wrap mode.
    pub specular_intensity_map_wrap_t: Option<String>,
    /// Specular intensity map magnification filter.
    pub specular_intensity_map_mag_filter: Option<String>,
    /// Specular intensity map minification filter.
    pub specular_intensity_map_min_filter: Option<String>,
    /// Specular intensity map UV transform `[a, c, tx, b, d, ty]`.
    pub specular_intensity_map_transform: Option<Vec<f64>>,
    /// Whether specular intensity map sampling uses the secondary UV stream.
    pub specular_intensity_map_uses_uv2: Option<bool>,
    /// MeshPhongMaterial specular color `[r, g, b]` in 0..1 range.
    pub specular_color: Option<Vec<f64>>,
    /// MeshPhongMaterial shininess. Defaults to 30.
    pub shininess: Option<f64>,
    /// Emissive color `[r, g, b]` in 0..1 range.
    pub emissive: Option<Vec<f64>>,
    /// Emissive intensity multiplier. Defaults to 1.
    pub emissive_intensity: Option<f64>,
    /// Optional normal map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub normal_map: Option<Buffer>,
    /// Normal map width in pixels (required when `normal_map` is raw RGBA8 bytes).
    pub normal_map_width: Option<u32>,
    /// Normal map height in pixels (required when `normal_map` is raw RGBA8 bytes).
    pub normal_map_height: Option<u32>,
    /// Normal map horizontal wrap mode.
    pub normal_map_wrap_s: Option<String>,
    /// Normal map vertical wrap mode.
    pub normal_map_wrap_t: Option<String>,
    /// Normal map magnification filter.
    pub normal_map_mag_filter: Option<String>,
    /// Normal map minification filter.
    pub normal_map_min_filter: Option<String>,
    /// Normal map UV transform `[a, c, tx, b, d, ty]`.
    pub normal_map_transform: Option<Vec<f64>>,
    /// Whether normal map sampling uses the secondary UV stream.
    pub normal_map_uses_uv2: Option<bool>,
    /// Normal map scale `[x, y]`. Defaults to `[1, 1]`.
    pub normal_scale: Option<Vec<f64>>,
    /// Optional bump map image data. Red channel is used as height.
    pub bump_map: Option<Buffer>,
    /// Bump map width (required when `bump_map` is raw RGBA8 bytes).
    pub bump_map_width: Option<u32>,
    /// Bump map height (required when `bump_map` is raw RGBA8 bytes).
    pub bump_map_height: Option<u32>,
    /// Bump map horizontal wrap mode.
    pub bump_map_wrap_s: Option<String>,
    /// Bump map vertical wrap mode.
    pub bump_map_wrap_t: Option<String>,
    /// Bump map magnification filter.
    pub bump_map_mag_filter: Option<String>,
    /// Bump map minification filter.
    pub bump_map_min_filter: Option<String>,
    /// Bump map UV transform `[a, c, tx, b, d, ty]`.
    pub bump_map_transform: Option<Vec<f64>>,
    /// Whether bump map sampling uses the secondary UV stream.
    pub bump_map_uses_uv2: Option<bool>,
    /// Bump map scale. Defaults to 1.
    pub bump_scale: Option<f64>,
    /// Optional MeshMatcapMaterial color map image data.
    pub matcap_map: Option<Buffer>,
    /// Matcap color map width (required when `matcap_map` is raw RGBA8 bytes).
    pub matcap_map_width: Option<u32>,
    /// Matcap color map height (required when `matcap_map` is raw RGBA8 bytes).
    pub matcap_map_height: Option<u32>,
    /// Matcap color map UV transform `[a, c, tx, b, d, ty]`.
    pub matcap_map_transform: Option<Vec<f64>>,
    /// Matcap color map color space: `"srgb"` or `"linear"`.
    pub matcap_map_color_space: Option<String>,
    /// Whether matcap color map sampling uses the secondary UV stream.
    pub matcap_map_uses_uv2: Option<bool>,
    /// MeshDepthMaterial packing mode. Uses Three.js constants: 3200 basic, 3201 RGBA, 3202 RGB, 3203 RG.
    pub depth_packing: Option<u32>,
    /// Optional MeshDistanceMaterial world-space reference position. Defaults to camera position.
    pub distance_reference_position: Option<Vec<f64>>,
    /// Optional MeshDistanceMaterial near distance. Defaults to camera near plane.
    pub distance_near: Option<f64>,
    /// Optional MeshDistanceMaterial far distance. Defaults to camera far plane.
    pub distance_far: Option<f64>,
    /// Optional MeshToonMaterial gradient ramp map. Red channel controls diffuse ramp strength.
    pub gradient_map: Option<Buffer>,
    /// Gradient map width (required when `gradient_map` is raw RGBA8 bytes).
    pub gradient_map_width: Option<u32>,
    /// Gradient map height (required when `gradient_map` is raw RGBA8 bytes).
    pub gradient_map_height: Option<u32>,
    /// Optional displacement map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    /// Red channel displaces vertices along their object-space normals.
    pub displacement_map: Option<Buffer>,
    /// Displacement map width in pixels (required when `displacement_map` is raw RGBA8 bytes).
    pub displacement_map_width: Option<u32>,
    /// Displacement map height in pixels (required when `displacement_map` is raw RGBA8 bytes).
    pub displacement_map_height: Option<u32>,
    /// Displacement map UV transform `[a, c, tx, b, d, ty]`.
    pub displacement_map_transform: Option<Vec<f64>>,
    /// Whether displacement map sampling uses the secondary UV stream.
    pub displacement_map_uses_uv2: Option<bool>,
    /// Displacement scale multiplier. Defaults to 1.
    pub displacement_scale: Option<f64>,
    /// Displacement bias added after map sampling. Defaults to 0.
    pub displacement_bias: Option<f64>,
    /// Optional emissive map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub emissive_map: Option<Buffer>,
    /// Emissive map width in pixels (required when `emissive_map` is raw RGBA8 bytes).
    pub emissive_map_width: Option<u32>,
    /// Emissive map height in pixels (required when `emissive_map` is raw RGBA8 bytes).
    pub emissive_map_height: Option<u32>,
    /// Emissive map horizontal wrap mode.
    pub emissive_map_wrap_s: Option<String>,
    /// Emissive map vertical wrap mode.
    pub emissive_map_wrap_t: Option<String>,
    /// Emissive map magnification filter.
    pub emissive_map_mag_filter: Option<String>,
    /// Emissive map minification filter.
    pub emissive_map_min_filter: Option<String>,
    /// Emissive map UV transform `[a, c, tx, b, d, ty]`.
    pub emissive_map_transform: Option<Vec<f64>>,
    /// Emissive texture color space. `"srgb"` is decoded to linear before shading.
    pub emissive_map_color_space: Option<String>,
    /// Whether emissive map sampling uses the secondary UV stream.
    pub emissive_map_uses_uv2: Option<bool>,
    /// Optional ambient occlusion map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    /// Red channel is used as the occlusion factor (Three.js / glTF convention).
    pub ao_map: Option<Buffer>,
    /// AO map width in pixels (required when `ao_map` is raw RGBA8 bytes).
    pub ao_map_width: Option<u32>,
    /// AO map height in pixels (required when `ao_map` is raw RGBA8 bytes).
    pub ao_map_height: Option<u32>,
    /// AO map horizontal wrap mode.
    pub ao_map_wrap_s: Option<String>,
    /// AO map vertical wrap mode.
    pub ao_map_wrap_t: Option<String>,
    /// AO map magnification filter.
    pub ao_map_mag_filter: Option<String>,
    /// AO map minification filter.
    pub ao_map_min_filter: Option<String>,
    /// AO map UV transform `[a, c, tx, b, d, ty]`.
    pub ao_map_transform: Option<Vec<f64>>,
    /// AO map intensity multiplier (0..1). Defaults to 1.
    pub ao_map_intensity: Option<f64>,
    /// Optional light map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    /// RGB channels add baked indirect diffuse lighting.
    pub light_map: Option<Buffer>,
    /// Light map width in pixels (required when `light_map` is raw RGBA8 bytes).
    pub light_map_width: Option<u32>,
    /// Light map height in pixels (required when `light_map` is raw RGBA8 bytes).
    pub light_map_height: Option<u32>,
    /// Light map horizontal wrap mode.
    pub light_map_wrap_s: Option<String>,
    /// Light map vertical wrap mode.
    pub light_map_wrap_t: Option<String>,
    /// Light map magnification filter.
    pub light_map_mag_filter: Option<String>,
    /// Light map minification filter.
    pub light_map_min_filter: Option<String>,
    /// Light map UV transform `[a, c, tx, b, d, ty]`.
    pub light_map_transform: Option<Vec<f64>>,
    /// Light-map texture color space. `"srgb"` is decoded to linear before shading.
    pub light_map_color_space: Option<String>,
    /// Light map intensity multiplier. Defaults to 1.
    pub light_map_intensity: Option<f64>,
    /// Optional alpha map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    /// Green channel multiplies material opacity, matching Three.js.
    pub alpha_map: Option<Buffer>,
    /// Alpha map width in pixels (required when `alpha_map` is raw RGBA8 bytes).
    pub alpha_map_width: Option<u32>,
    /// Alpha map height in pixels (required when `alpha_map` is raw RGBA8 bytes).
    pub alpha_map_height: Option<u32>,
    /// Alpha map horizontal wrap mode.
    pub alpha_map_wrap_s: Option<String>,
    /// Alpha map vertical wrap mode.
    pub alpha_map_wrap_t: Option<String>,
    /// Alpha map magnification filter.
    pub alpha_map_mag_filter: Option<String>,
    /// Alpha map minification filter.
    pub alpha_map_min_filter: Option<String>,
    /// Alpha map UV transform `[a, c, tx, b, d, ty]`.
    pub alpha_map_transform: Option<Vec<f64>>,
    /// Whether alpha map sampling uses the secondary UV stream.
    pub alpha_map_uses_uv2: Option<bool>,
    /// Alpha test cutoff threshold (0..1). Fragments with alpha below this are discarded.
    pub alpha_test: Option<f64>,
    /// Whether to apply stochastic alpha hashing before depth/color writes.
    pub alpha_hash: Option<bool>,
    /// Whether fragment RGB output is multiplied by output alpha before blending.
    pub premultiplied_alpha: Option<bool>,
    /// Flattened world-space clipping planes `[nx, ny, nz, constant, ...]`, up to 8 planes.
    /// Fragments with `dot(normal, worldPosition) + constant < 0` are clipped.
    pub clipping_planes: Option<Vec<f64>>,
    /// Number of leading clipping planes evaluated as union planes. Remaining planes use
    /// intersection semantics. Defaults to all planes as union planes.
    pub clipping_union_count: Option<u32>,
    /// Whether the mesh is transparent (sorted back-to-front, no depth write).
    pub transparent: Option<bool>,
    /// Material blending mode: `"none"`, `"normal"`, `"additive"`, `"subtractive"`, `"multiply"`, or `"custom"`.
    pub blending: Option<String>,
    /// Custom blending equation constants when `blending` is `"custom"`.
    pub blend_equation: Option<u32>,
    pub blend_src: Option<u32>,
    pub blend_dst: Option<u32>,
    pub blend_equation_alpha: Option<u32>,
    pub blend_src_alpha: Option<u32>,
    pub blend_dst_alpha: Option<u32>,
    /// Custom blend constant color `[r, g, b]`.
    pub blend_color: Option<Vec<f64>>,
    /// Custom blend constant alpha.
    pub blend_alpha: Option<f64>,
    /// Whether depth testing is enabled. Defaults to true.
    pub depth_test: Option<bool>,
    /// Whether passing fragments write depth. Defaults to true for opaque meshes and false for transparent meshes.
    pub depth_write: Option<bool>,
    /// Whether fragments write color. Defaults to true.
    pub color_write: Option<bool>,
    /// Whether to apply material polygon offset as depth bias in the main pass.
    pub polygon_offset: Option<bool>,
    /// Slope-scaled polygon offset factor.
    pub polygon_offset_factor: Option<f64>,
    /// Constant polygon offset units.
    pub polygon_offset_units: Option<f64>,
    /// Whether stencil testing/writes are enabled for this material.
    pub stencil_write: Option<bool>,
    /// Stencil write bit mask. Defaults to 0xff.
    pub stencil_write_mask: Option<u32>,
    /// Stencil comparison function constant. Defaults to AlwaysStencilFunc.
    pub stencil_func: Option<u32>,
    /// Stencil reference value. Defaults to 0.
    pub stencil_ref: Option<u32>,
    /// Stencil comparison bit mask. Defaults to 0xff.
    pub stencil_func_mask: Option<u32>,
    /// Operation when the stencil test fails. Defaults to KeepStencilOp.
    pub stencil_fail: Option<u32>,
    /// Operation when the stencil test passes but depth fails. Defaults to KeepStencilOp.
    pub stencil_z_fail: Option<u32>,
    /// Operation when both stencil and depth pass. Defaults to KeepStencilOp.
    pub stencil_z_pass: Option<u32>,
    /// Which faces to render: `"front"` (default), `"back"`, or `"double"`.
    pub side: Option<String>,
    /// Shading model: `"standard"` (default PBR), `"basic"` (unlit / MeshBasicMaterial),
    /// or `"lambert"` (diffuse-only / MeshLambertMaterial).
    pub shading_model: Option<String>,
    /// Primitive topology: `"triangles"` (default), `"lines"` (LineList), or `"points"`.
    pub topology: Option<String>,
    /// WGSL fragment shader body for the custom material path.
    pub custom_fragment_shader: Option<String>,
    /// Whether this mesh casts shadows in the shadow pass. Defaults to false.
    pub cast_shadow: Option<bool>,
    /// Whether this mesh receives shadows in the main pass. Defaults to false.
    pub receive_shadow: Option<bool>,
    /// Three.js groupOrder inherited from the nearest Group.renderOrder. Defaults to 0.
    pub group_order: Option<f64>,
    /// Explicit Three.js object renderOrder. Defaults to 0.
    pub render_order: Option<f64>,
    /// Projected camera-space sort key provided by the Three.js adapter.
    pub sort_z: Option<f64>,
    /// Stable object id / adapter insertion-order tie-breaker.
    pub sort_index: Option<u32>,
    /// Material id sort key used for opaque draw ordering.
    pub material_sort_key: Option<u32>,
}

#[napi(object)]
#[derive(Clone, Debug, Default)]
pub struct Camera {
    /// Output width in pixels.
    pub width: Option<u32>,
    /// Output height in pixels.
    pub height: Option<u32>,
    /// Camera position. Defaults to `[2.5, 1.8, 3.2]`.
    pub eye: Option<Vec<f64>>,
    /// Look-at target. Defaults to `[0, 0, 0]`.
    pub target: Option<Vec<f64>>,
    /// Up direction. Defaults to `[0, 1, 0]`.
    pub up: Option<Vec<f64>>,
    /// Vertical field of view in degrees. Defaults to `45`.
    pub fov_y_degrees: Option<f64>,
    /// Near clipping plane. Defaults to `0.01`.
    pub near: Option<f64>,
    /// Far clipping plane. Defaults to `100`.
    pub far: Option<f64>,
    /// Optional column-major 4x4 view-projection matrix in WebGPU clip space.
    pub view_projection: Option<Vec<f64>>,
    /// Optional column-major 4x4 view matrix.
    pub view_matrix: Option<Vec<f64>>,
    /// Camera world position `[x, y, z]` for PBR lighting.
    pub camera_position: Option<Vec<f64>>,
}
