use napi::bindgen_prelude::Buffer;
use napi_derive::napi;

#[napi(object)]
#[derive(Default)]
pub struct RenderScene {
    /// Output width in pixels. `camera.width` takes precedence when set.
    pub width: Option<u32>,
    /// Output height in pixels. `camera.height` takes precedence when set.
    pub height: Option<u32>,
    /// Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range.
    pub background: Option<Vec<f64>>,
    /// Output format. Supported values are `"png"` (default) and `"rgba"`.
    pub format: Option<String>,
    /// Triangle-list meshes generated by the JavaScript Three.js adapter.
    pub meshes: Option<Vec<SceneMesh>>,
    /// Scene lights.
    pub lights: Option<Vec<SceneLight>>,
    /// Ambient light color `[r, g, b]` in 0..1 range.
    pub ambient_light: Option<Vec<f64>>,
    /// Ambient light intensity. Defaults to 0.
    pub ambient_intensity: Option<f64>,
    /// Optional environment map image data (equirectangular HDR/LDR, encoded or raw RGBA/Float).
    pub environment_map: Option<Buffer>,
    /// Environment map width in pixels (required when data is raw typed-array bytes).
    pub environment_map_width: Option<u32>,
    /// Environment map height in pixels (required when data is raw typed-array bytes).
    pub environment_map_height: Option<u32>,
    /// Environment map intensity multiplier. Defaults to 1.
    pub environment_map_intensity: Option<f64>,
    /// Post-processing exposure adjustment in stops. Defaults to 0.
    pub post_exposure: Option<f64>,
    /// Post-processing contrast multiplier. Defaults to 1.
    pub post_contrast: Option<f64>,
    /// Post-processing saturation multiplier. Defaults to 1.
    pub post_saturation: Option<f64>,
    /// Post-processing vignette amount 0..1. Defaults to 0.
    pub post_vignette: Option<f64>,
    /// Post-processing grayscale blend 0..1. Defaults to 0.
    pub post_grayscale: Option<f64>,
    /// Post-processing inversion blend 0..1. Defaults to 0.
    pub post_invert: Option<f64>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneLight {
    /// Light type: `"directional"`, `"point"`, `"spot"`, or `"hemisphere"`.
    pub light_type: String,
    /// Light color `[r, g, b]` in 0..1 range.
    pub color: Option<Vec<f64>>,
    /// Light intensity.
    pub intensity: Option<f64>,
    /// World-space position `[x, y, z]` (point and spot lights).
    pub position: Option<Vec<f64>>,
    /// Direction `[x, y, z]` (directional and spot lights, up for hemisphere).
    pub direction: Option<Vec<f64>>,
    /// Maximum range. 0 = infinite (point and spot).
    pub distance: Option<f64>,
    /// Decay exponent for distance falloff (point and spot). Defaults to 2.
    pub decay: Option<f64>,
    /// Spotlight half-angle in radians. Defaults to π/3.
    pub angle: Option<f64>,
    /// Spotlight penumbra 0..1. Defaults to 0.
    pub penumbra: Option<f64>,
    /// Hemisphere light ground color `[r, g, b]` in 0..1 range.
    pub ground_color: Option<Vec<f64>>,
    /// Whether this light casts shadows (directional, spot, and point lights).
    pub cast_shadow: Option<bool>,
    /// Shadow map resolution (square, pixels). Defaults to 512.
    pub shadow_map_size: Option<u32>,
    /// Depth bias in shadow-map NDC.
    pub shadow_bias: Option<f64>,
    /// Normal-offset bias in world space at the receiver.
    pub shadow_normal_bias: Option<f64>,
    /// Orthographic shadow-camera frustum bounds.
    pub shadow_camera_left: Option<f64>,
    pub shadow_camera_right: Option<f64>,
    pub shadow_camera_top: Option<f64>,
    pub shadow_camera_bottom: Option<f64>,
    pub shadow_camera_near: Option<f64>,
    pub shadow_camera_far: Option<f64>,
    /// Cascaded shadow split distances from the active camera.
    pub shadow_cascade_splits: Option<Vec<f64>>,
    /// Flattened cascade bounds: `[left, right, top, bottom, near, far, ...]`.
    pub shadow_cascade_bounds: Option<Vec<f64>>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneMesh {
    /// Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`.
    pub positions: Vec<f64>,
    /// Optional uint32 triangle-list indices.
    pub indices: Option<Vec<u32>>,
    /// Optional per-vertex normals: `[nx0, ny0, nz0, ...]`.
    pub normals: Option<Vec<f64>>,
    /// Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex.
    pub colors: Option<Vec<f64>>,
    /// Mesh material color used when `colors` is omitted.
    pub color: Option<Vec<f64>>,
    /// Optional column-major 4x4 model matrix.
    pub transform: Option<Vec<f64>>,
    /// Optional per-vertex UV coordinates: `[u0, v0, u1, v1, ...]`.
    pub uvs: Option<Vec<f64>>,
    /// Optional texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub texture: Option<Buffer>,
    /// Texture width in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_width: Option<u32>,
    /// Texture height in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_height: Option<u32>,
    /// Texture horizontal wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub texture_wrap_s: Option<String>,
    /// Texture vertical wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub texture_wrap_t: Option<String>,
    /// Optional metallic-roughness texture (glTF convention: G=roughness, B=metallic).
    pub metallic_roughness_texture: Option<Buffer>,
    /// Metallic-roughness texture width (required when texture is raw RGBA8 bytes).
    pub metallic_roughness_texture_width: Option<u32>,
    /// Metallic-roughness texture height (required when texture is raw RGBA8 bytes).
    pub metallic_roughness_texture_height: Option<u32>,
    /// Metallic factor (0..1). Defaults to 0.
    pub metallic: Option<f64>,
    /// Roughness factor (0..1). Defaults to 1.
    pub roughness: Option<f64>,
    /// Clearcoat intensity (0..1) for MeshPhysicalMaterial. Defaults to 0.
    pub clearcoat: Option<f64>,
    /// Optional clearcoat intensity map. Red channel multiplies `clearcoat`.
    pub clearcoat_map: Option<Buffer>,
    /// Clearcoat map width (required when map is raw RGBA8 bytes).
    pub clearcoat_map_width: Option<u32>,
    /// Clearcoat map height (required when map is raw RGBA8 bytes).
    pub clearcoat_map_height: Option<u32>,
    /// Clearcoat roughness (0..1). Defaults to 0.
    pub clearcoat_roughness: Option<f64>,
    /// Optional clearcoat roughness map. Green channel multiplies `clearcoatRoughness`.
    pub clearcoat_roughness_map: Option<Buffer>,
    /// Clearcoat roughness map width (required when map is raw RGBA8 bytes).
    pub clearcoat_roughness_map_width: Option<u32>,
    /// Clearcoat roughness map height (required when map is raw RGBA8 bytes).
    pub clearcoat_roughness_map_height: Option<u32>,
    /// Optional clearcoat normal map.
    pub clearcoat_normal_map: Option<Buffer>,
    /// Clearcoat normal map width (required when map is raw RGBA8 bytes).
    pub clearcoat_normal_map_width: Option<u32>,
    /// Clearcoat normal map height (required when map is raw RGBA8 bytes).
    pub clearcoat_normal_map_height: Option<u32>,
    /// Clearcoat normal map scale `[x, y]`. Defaults to `[1, 1]`.
    pub clearcoat_normal_scale: Option<Vec<f64>>,
    /// Sheen color/intensity `[r, g, b]` in 0..1 range.
    pub sheen_color: Option<Vec<f64>>,
    /// Optional sheen color map. RGB channels multiply `sheenColor`.
    pub sheen_color_map: Option<Buffer>,
    /// Sheen color map width (required when map is raw RGBA8 bytes).
    pub sheen_color_map_width: Option<u32>,
    /// Sheen color map height (required when map is raw RGBA8 bytes).
    pub sheen_color_map_height: Option<u32>,
    /// Sheen roughness (0..1). Defaults to 1 when sheen is present.
    pub sheen_roughness: Option<f64>,
    /// Optional sheen roughness map. Alpha channel multiplies `sheenRoughness`.
    pub sheen_roughness_map: Option<Buffer>,
    /// Sheen roughness map width (required when map is raw RGBA8 bytes).
    pub sheen_roughness_map_width: Option<u32>,
    /// Sheen roughness map height (required when map is raw RGBA8 bytes).
    pub sheen_roughness_map_height: Option<u32>,
    /// Anisotropy strength (0..1). Defaults to 0.
    pub anisotropy: Option<f64>,
    /// Anisotropy rotation in tangent space, radians.
    pub anisotropy_rotation: Option<f64>,
    /// Optional anisotropy map. RG encode direction and B encodes strength.
    pub anisotropy_map: Option<Buffer>,
    /// Anisotropy map width (required when map is raw RGBA8 bytes).
    pub anisotropy_map_width: Option<u32>,
    /// Anisotropy map height (required when map is raw RGBA8 bytes).
    pub anisotropy_map_height: Option<u32>,
    /// Physical transmission factor (0..1). Defaults to 0.
    pub transmission: Option<f64>,
    /// Optional transmission map. Red channel multiplies `transmission`.
    pub transmission_map: Option<Buffer>,
    /// Transmission map width (required when map is raw RGBA8 bytes).
    pub transmission_map_width: Option<u32>,
    /// Transmission map height (required when map is raw RGBA8 bytes).
    pub transmission_map_height: Option<u32>,
    /// Index of refraction for physical materials. Defaults to 1.5.
    pub ior: Option<f64>,
    /// Transmission volume thickness in model units. Defaults to 0.
    pub thickness: Option<f64>,
    /// Optional thickness map. Green channel multiplies `thickness`.
    pub thickness_map: Option<Buffer>,
    /// Thickness map width (required when map is raw RGBA8 bytes).
    pub thickness_map_width: Option<u32>,
    /// Thickness map height (required when map is raw RGBA8 bytes).
    pub thickness_map_height: Option<u32>,
    /// Transmission attenuation distance. Defaults to a very large distance.
    pub attenuation_distance: Option<f64>,
    /// Transmission attenuation color `[r, g, b]` in 0..1 range.
    pub attenuation_color: Option<Vec<f64>>,
    /// Emissive color `[r, g, b]` in 0..1 range.
    pub emissive: Option<Vec<f64>>,
    /// Emissive intensity multiplier. Defaults to 1.
    pub emissive_intensity: Option<f64>,
    /// Optional normal map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub normal_map: Option<Buffer>,
    /// Normal map width in pixels (required when `normal_map` is raw RGBA8 bytes).
    pub normal_map_width: Option<u32>,
    /// Normal map height in pixels (required when `normal_map` is raw RGBA8 bytes).
    pub normal_map_height: Option<u32>,
    /// Normal map scale `[x, y]`. Defaults to `[1, 1]`.
    pub normal_scale: Option<Vec<f64>>,
    /// Optional emissive map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub emissive_map: Option<Buffer>,
    /// Emissive map width in pixels (required when `emissive_map` is raw RGBA8 bytes).
    pub emissive_map_width: Option<u32>,
    /// Emissive map height in pixels (required when `emissive_map` is raw RGBA8 bytes).
    pub emissive_map_height: Option<u32>,
    /// Optional ambient occlusion map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    /// Red channel is used as the occlusion factor (Three.js / glTF convention).
    pub ao_map: Option<Buffer>,
    /// AO map width in pixels (required when `ao_map` is raw RGBA8 bytes).
    pub ao_map_width: Option<u32>,
    /// AO map height in pixels (required when `ao_map` is raw RGBA8 bytes).
    pub ao_map_height: Option<u32>,
    /// AO map intensity multiplier (0..1). Defaults to 1.
    pub ao_map_intensity: Option<f64>,
    /// Alpha test cutoff threshold (0..1). Fragments with alpha below this are discarded.
    pub alpha_test: Option<f64>,
    /// Whether the mesh is transparent (sorted back-to-front, no depth write).
    pub transparent: Option<bool>,
    /// Which faces to render: `"front"` (default), `"back"`, or `"double"`.
    pub side: Option<String>,
    /// Shading model: `"standard"` (default PBR), `"basic"` (unlit / MeshBasicMaterial),
    /// or `"lambert"` (diffuse-only / MeshLambertMaterial).
    pub shading_model: Option<String>,
    /// Primitive topology: `"triangles"` (default), `"lines"` (LineList), or `"points"`.
    pub topology: Option<String>,
    /// WGSL fragment shader body for the custom material path.
    pub custom_fragment_shader: Option<String>,
    /// Whether this mesh casts shadows in the shadow pass. Defaults to false.
    pub cast_shadow: Option<bool>,
    /// Whether this mesh receives shadows in the main pass. Defaults to false.
    pub receive_shadow: Option<bool>,
}

#[napi(object)]
#[derive(Clone, Debug, Default)]
pub struct Camera {
    /// Output width in pixels.
    pub width: Option<u32>,
    /// Output height in pixels.
    pub height: Option<u32>,
    /// Camera position. Defaults to `[2.5, 1.8, 3.2]`.
    pub eye: Option<Vec<f64>>,
    /// Look-at target. Defaults to `[0, 0, 0]`.
    pub target: Option<Vec<f64>>,
    /// Up direction. Defaults to `[0, 1, 0]`.
    pub up: Option<Vec<f64>>,
    /// Vertical field of view in degrees. Defaults to `45`.
    pub fov_y_degrees: Option<f64>,
    /// Near clipping plane. Defaults to `0.01`.
    pub near: Option<f64>,
    /// Far clipping plane. Defaults to `100`.
    pub far: Option<f64>,
    /// Optional column-major 4x4 view-projection matrix in WebGPU clip space.
    pub view_projection: Option<Vec<f64>>,
    /// Camera world position `[x, y, z]` for PBR lighting.
    pub camera_position: Option<Vec<f64>>,
}
