import { NativeSceneLight } from './types.part-002'
export interface NativeSceneMesh {
  nativeMeshKey?: number
  nativeVertexCount?: number
  nativeIndexCount?: number
  positions: number[]
  indices?: number[]
  normals?: number[]
  colors?: number[]
  color?: number[]
  transform?: number[]
  uvs?: number[]
  uvs2?: number[]
  texture?: Buffer
  textureWidth?: number
  textureHeight?: number
  textureWrapS?: string
  textureWrapT?: string
  textureMagFilter?: string
  textureMinFilter?: string
  textureAnisotropy?: number
  textureTransform?: number[]
  textureColorSpace?: string
  textureUsesUv2?: boolean
  specularColor?: number[]
  shininess?: number
  metallic?: number
  roughness?: number
  clearcoat?: number
  clearcoatMap?: Buffer
  clearcoatMapWidth?: number
  clearcoatMapHeight?: number
  clearcoatMapWrapS?: string
  clearcoatMapWrapT?: string
  clearcoatMapMagFilter?: string
  clearcoatMapMinFilter?: string
  clearcoatMapAnisotropy?: number
  clearcoatMapTransform?: number[]
  clearcoatMapColorSpace?: string
  clearcoatMapUsesUv2?: boolean
  clearcoatRoughness?: number
  clearcoatRoughnessMap?: Buffer
  clearcoatRoughnessMapWidth?: number
  clearcoatRoughnessMapHeight?: number
  clearcoatRoughnessMapWrapS?: string
  clearcoatRoughnessMapWrapT?: string
  clearcoatRoughnessMapMagFilter?: string
  clearcoatRoughnessMapMinFilter?: string
  clearcoatRoughnessMapAnisotropy?: number
  clearcoatRoughnessMapTransform?: number[]
  clearcoatRoughnessMapColorSpace?: string
  clearcoatRoughnessMapUsesUv2?: boolean
  clearcoatNormalMap?: Buffer
  clearcoatNormalMapWidth?: number
  clearcoatNormalMapHeight?: number
  clearcoatNormalMapWrapS?: string
  clearcoatNormalMapWrapT?: string
  clearcoatNormalMapMagFilter?: string
  clearcoatNormalMapMinFilter?: string
  clearcoatNormalMapAnisotropy?: number
  clearcoatNormalMapTransform?: number[]
  clearcoatNormalMapColorSpace?: string
  clearcoatNormalMapUsesUv2?: boolean
  clearcoatNormalScale?: number[]
  sheenColor?: number[]
  sheenColorMap?: Buffer
  sheenColorMapWidth?: number
  sheenColorMapHeight?: number
  sheenColorMapWrapS?: string
  sheenColorMapWrapT?: string
  sheenColorMapMagFilter?: string
  sheenColorMapMinFilter?: string
  sheenColorMapAnisotropy?: number
  sheenColorMapTransform?: number[]
  sheenColorMapColorSpace?: string
  sheenColorMapUsesUv2?: boolean
  sheenRoughness?: number
  sheenRoughnessMap?: Buffer
  sheenRoughnessMapWidth?: number
  sheenRoughnessMapHeight?: number
  sheenRoughnessMapWrapS?: string
  sheenRoughnessMapWrapT?: string
  sheenRoughnessMapMagFilter?: string
  sheenRoughnessMapMinFilter?: string
  sheenRoughnessMapAnisotropy?: number
  sheenRoughnessMapTransform?: number[]
  sheenRoughnessMapColorSpace?: string
  sheenRoughnessMapUsesUv2?: boolean
  anisotropy?: number
  anisotropyRotation?: number
  anisotropyMap?: Buffer
  anisotropyMapWidth?: number
  anisotropyMapHeight?: number
  anisotropyMapWrapS?: string
  anisotropyMapWrapT?: string
  anisotropyMapMagFilter?: string
  anisotropyMapMinFilter?: string
  anisotropyMapAnisotropy?: number
  anisotropyMapTransform?: number[]
  anisotropyMapColorSpace?: string
  anisotropyMapUsesUv2?: boolean
  iridescence?: number
  iridescenceMap?: Buffer
  iridescenceMapWidth?: number
  iridescenceMapHeight?: number
  iridescenceMapWrapS?: string
  iridescenceMapWrapT?: string
  iridescenceMapMagFilter?: string
  iridescenceMapMinFilter?: string
  iridescenceMapAnisotropy?: number
  iridescenceMapTransform?: number[]
  iridescenceMapColorSpace?: string
  iridescenceMapUsesUv2?: boolean
  iridescenceIor?: number
  iridescenceThicknessMin?: number
  iridescenceThicknessMax?: number
  iridescenceThicknessMap?: Buffer
  iridescenceThicknessMapWidth?: number
  iridescenceThicknessMapHeight?: number
  iridescenceThicknessMapWrapS?: string
  iridescenceThicknessMapWrapT?: string
  iridescenceThicknessMapMagFilter?: string
  iridescenceThicknessMapMinFilter?: string
  iridescenceThicknessMapAnisotropy?: number
  iridescenceThicknessMapTransform?: number[]
  iridescenceThicknessMapColorSpace?: string
  iridescenceThicknessMapUsesUv2?: boolean
  transmission?: number
  transmissionMap?: Buffer
  transmissionMapWidth?: number
  transmissionMapHeight?: number
  transmissionMapWrapS?: string
  transmissionMapWrapT?: string
  transmissionMapMagFilter?: string
  transmissionMapMinFilter?: string
  transmissionMapAnisotropy?: number
  transmissionMapTransform?: number[]
  transmissionMapColorSpace?: string
  transmissionMapUsesUv2?: boolean
  dispersion?: number
  ior?: number
  thickness?: number
  thicknessMap?: Buffer
  thicknessMapWidth?: number
  thicknessMapHeight?: number
  thicknessMapWrapS?: string
  thicknessMapWrapT?: string
  thicknessMapMagFilter?: string
  thicknessMapMinFilter?: string
  thicknessMapAnisotropy?: number
  thicknessMapTransform?: number[]
  thicknessMapColorSpace?: string
  thicknessMapUsesUv2?: boolean
  attenuationDistance?: number
  attenuationColor?: number[]
  physicalSpecularColor?: number[]
  physicalSpecularIntensity?: number
  specularColorMap?: Buffer
  specularColorMapWidth?: number
  specularColorMapHeight?: number
  specularColorMapWrapS?: string
  specularColorMapWrapT?: string
  specularColorMapMagFilter?: string
  specularColorMapMinFilter?: string
  specularColorMapAnisotropy?: number
  specularColorMapTransform?: number[]
  specularColorMapColorSpace?: string
  specularColorMapUsesUv2?: boolean
  specularIntensityMap?: Buffer
  specularIntensityMapWidth?: number
  specularIntensityMapHeight?: number
  specularIntensityMapWrapS?: string
  specularIntensityMapWrapT?: string
  specularIntensityMapMagFilter?: string
  specularIntensityMapMinFilter?: string
  specularIntensityMapAnisotropy?: number
  specularIntensityMapTransform?: number[]
  specularIntensityMapColorSpace?: string
  specularIntensityMapUsesUv2?: boolean
  emissive?: number[]
  emissiveIntensity?: number
  normalMap?: Buffer
  normalMapWidth?: number
  normalMapHeight?: number
  normalMapWrapS?: string
  normalMapWrapT?: string
  normalMapMagFilter?: string
  normalMapMinFilter?: string
  normalMapAnisotropy?: number
  normalMapTransform?: number[]
  normalMapColorSpace?: string
  normalMapUsesUv2?: boolean
  normalMapType?: 'tangent' | 'object'
  normalScale?: number[]
  bumpMap?: Buffer
  bumpMapWidth?: number
  bumpMapHeight?: number
  bumpMapWrapS?: string
  bumpMapWrapT?: string
  bumpMapMagFilter?: string
  bumpMapMinFilter?: string
  bumpMapAnisotropy?: number
  bumpMapTransform?: number[]
  bumpMapColorSpace?: string
  bumpMapUsesUv2?: boolean
  bumpScale?: number
  matcapMap?: Buffer
  matcapMapWidth?: number
  matcapMapHeight?: number
  matcapMapWrapS?: string
  matcapMapWrapT?: string
  matcapMapMagFilter?: string
  matcapMapMinFilter?: string
  matcapMapAnisotropy?: number
  matcapMapTransform?: number[]
  matcapMapColorSpace?: string
  matcapMapUsesUv2?: boolean
  depthPacking?: number
  distanceReferencePosition?: number[]
  distanceNear?: number
  distanceFar?: number
  gradientMap?: Buffer
  gradientMapWidth?: number
  gradientMapHeight?: number
  gradientMapWrapS?: string
  gradientMapWrapT?: string
  gradientMapMagFilter?: string
  gradientMapMinFilter?: string
  gradientMapAnisotropy?: number
  gradientMapColorSpace?: string
  displacementMap?: Buffer
  displacementMapWidth?: number
  displacementMapHeight?: number
  displacementMapWrapS?: string
  displacementMapWrapT?: string
  displacementMapMagFilter?: string
  displacementMapMinFilter?: string
  displacementMapAnisotropy?: number
  displacementMapTransform?: number[]
  displacementMapColorSpace?: string
  displacementMapUsesUv2?: boolean
  displacementScale?: number
  displacementBias?: number
  metallicRoughnessTexture?: Buffer
  metallicRoughnessTextureWidth?: number
  metallicRoughnessTextureHeight?: number
  metallicRoughnessTextureWrapS?: string
  metallicRoughnessTextureWrapT?: string
  metallicRoughnessTextureMagFilter?: string
  metallicRoughnessTextureMinFilter?: string
  metallicRoughnessTextureAnisotropy?: number
  metallicRoughnessTextureTransform?: number[]
  metallicRoughnessTextureColorSpace?: string
  metallicRoughnessTextureUsesUv2?: boolean
  emissiveMap?: Buffer
  emissiveMapWidth?: number
  emissiveMapHeight?: number
  emissiveMapWrapS?: string
  emissiveMapWrapT?: string
  emissiveMapMagFilter?: string
  emissiveMapMinFilter?: string
  emissiveMapAnisotropy?: number
  emissiveMapTransform?: number[]
  emissiveMapColorSpace?: string
  emissiveMapUsesUv2?: boolean
  aoMap?: Buffer
  aoMapWidth?: number
  aoMapHeight?: number
  aoMapWrapS?: string
  aoMapWrapT?: string
  aoMapMagFilter?: string
  aoMapMinFilter?: string
  aoMapAnisotropy?: number
  aoMapTransform?: number[]
  aoMapColorSpace?: string
  aoMapUsesUv2?: boolean
  aoMapIntensity?: number
  lightMap?: Buffer
  lightMapWidth?: number
  lightMapHeight?: number
  lightMapWrapS?: string
  lightMapWrapT?: string
  lightMapMagFilter?: string
  lightMapMinFilter?: string
  lightMapAnisotropy?: number
  lightMapTransform?: number[]
  lightMapColorSpace?: string
  lightMapUsesUv2?: boolean
  lightMapIntensity?: number
  specularMap?: Buffer
  specularMapWidth?: number
  specularMapHeight?: number
  specularMapWrapS?: string
  specularMapWrapT?: string
  specularMapMagFilter?: string
  specularMapMinFilter?: string
  specularMapAnisotropy?: number
  specularMapTransform?: number[]
  specularMapColorSpace?: string
  specularMapUsesUv2?: boolean
  alphaMap?: Buffer
  alphaMapWidth?: number
  alphaMapHeight?: number
  alphaMapWrapS?: string
  alphaMapWrapT?: string
  alphaMapMagFilter?: string
  alphaMapMinFilter?: string
  alphaMapAnisotropy?: number
  alphaMapTransform?: number[]
  alphaMapColorSpace?: string
  alphaMapUsesUv2?: boolean
  alphaTest?: number
  alphaHash?: boolean
  alphaToCoverage?: boolean
  premultipliedAlpha?: boolean
  toneMapped?: boolean
  flatShading?: boolean
  fog?: boolean
  /** Flattened world-space clipping planes `[nx, ny, nz, constant, ...]`, up to 8 planes. */
  clippingPlanes?: number[]
  /** Number of leading clipping planes evaluated as union planes; remaining planes use intersection semantics. */
  clippingUnionCount?: number
  /** Whether material clipping planes affect this mesh in the shadow pass. */
  clipShadows?: boolean
  blending?: string
  blendEquation?: number
  blendSrc?: number
  blendDst?: number
  blendEquationAlpha?: number
  blendSrcAlpha?: number
  blendDstAlpha?: number
  blendColor?: number[]
  blendAlpha?: number
  depthTest?: boolean
  depthFunc?: string
  depthWrite?: boolean
  colorWrite?: boolean
  polygonOffset?: boolean
  polygonOffsetFactor?: number
  polygonOffsetUnits?: number
  stencilWrite?: boolean
  stencilWriteMask?: number
  stencilFunc?: number
  stencilRef?: number
  stencilFuncMask?: number
  stencilFail?: number
  stencilZFail?: number
  stencilZPass?: number
  transparent?: boolean
  side?: string
  /** Optional shadow-pass face filter from material.shadowSide. Unset preserves the renderer's default no-cull caster behavior. */
  shadowSide?: string
  shadingModel?: string
  useEnvironmentMap?: boolean
  environmentMapIntensity?: number
  environmentMapCombine?: number
  environmentMapReflectivity?: number
  environmentMapRefraction?: boolean
  environmentMapRefractionRatio?: number
  topology?: string
  /** WGSL fragment body used by the custom material path. */
  customFragmentShader?: string
  /** Whether this mesh casts shadows in the shadow pass. Defaults to false. */
  castShadow?: boolean
  /** Whether this mesh receives shadows in the main pass. Defaults to false. */
  receiveShadow?: boolean
  groupOrder?: number
  renderOrder?: number
  sortZ?: number
  sortIndex?: number
  materialVariant?: number
  materialSortKey?: number
}

export interface NativeRenderScene {
  width?: number
  height?: number
  background?: number[]
  backgroundIntensity?: number
  viewport?: number[]
  scissor?: number[]
  backgroundTexture?: Buffer
  backgroundTextureWidth?: number
  backgroundTextureHeight?: number
  backgroundTextureWrapS?: string
  backgroundTextureWrapT?: string
  backgroundTextureMagFilter?: string
  backgroundTextureMinFilter?: string
  backgroundTextureAnisotropy?: number
  backgroundTextureTransform?: number[]
  backgroundTextureColorSpace?: string
  backgroundTextureMapping?: string
  backgroundTextureRotation?: number[]
  backgroundTextureBlurriness?: number
  format?: string
  outputColorSpace?: string
  toneMapping?: number
  toneMappingExposure?: number
  transmissionResolutionScale?: number
  sampleCount?: number
  shadowMapType?: number
  meshes?: NativeSceneMesh[]
  lights?: NativeSceneLight[]
  ambientLight?: number[]
  ambientIntensity?: number
  lightProbe?: number[]
  environmentMap?: Buffer
  environmentMapWidth?: number
  environmentMapHeight?: number
  environmentMapIntensity?: number
  environmentMapColorSpace?: string
  environmentMapRotation?: number[]
  fogType?: string
  fogColor?: number[]
  fogNear?: number
  fogFar?: number
  fogDensity?: number
  postExposure?: number
  postContrast?: number
  postSaturation?: number
  postVignette?: number
  postGrayscale?: number
  postInvert?: number
}

// ── Internal helper types ───────────────────────────────────────────

export type Color4 = [number, number, number, number]
export type Mat4 = number[]
export type Vec3 = [number, number, number]
