export interface PbrProperties {
  metallic?: number
  roughness?: number
  clearcoat?: number
  clearcoatMap?: Buffer
  clearcoatMapWidth?: number
  clearcoatMapHeight?: number
  clearcoatMapWrapS?: string
  clearcoatMapWrapT?: string
  clearcoatMapMagFilter?: string
  clearcoatMapMinFilter?: string
  clearcoatMapAnisotropy?: number
  clearcoatMapTransform?: number[]
  clearcoatMapColorSpace?: string
  clearcoatMapUsesUv2?: boolean
  clearcoatRoughness?: number
  clearcoatRoughnessMap?: Buffer
  clearcoatRoughnessMapWidth?: number
  clearcoatRoughnessMapHeight?: number
  clearcoatRoughnessMapWrapS?: string
  clearcoatRoughnessMapWrapT?: string
  clearcoatRoughnessMapMagFilter?: string
  clearcoatRoughnessMapMinFilter?: string
  clearcoatRoughnessMapAnisotropy?: number
  clearcoatRoughnessMapTransform?: number[]
  clearcoatRoughnessMapColorSpace?: string
  clearcoatRoughnessMapUsesUv2?: boolean
  clearcoatNormalMap?: Buffer
  clearcoatNormalMapWidth?: number
  clearcoatNormalMapHeight?: number
  clearcoatNormalMapWrapS?: string
  clearcoatNormalMapWrapT?: string
  clearcoatNormalMapMagFilter?: string
  clearcoatNormalMapMinFilter?: string
  clearcoatNormalMapAnisotropy?: number
  clearcoatNormalMapTransform?: number[]
  clearcoatNormalMapColorSpace?: string
  clearcoatNormalMapUsesUv2?: boolean
  clearcoatNormalScale?: number[]
  sheenColor?: number[]
  sheenColorMap?: Buffer
  sheenColorMapWidth?: number
  sheenColorMapHeight?: number
  sheenColorMapWrapS?: string
  sheenColorMapWrapT?: string
  sheenColorMapMagFilter?: string
  sheenColorMapMinFilter?: string
  sheenColorMapAnisotropy?: number
  sheenColorMapTransform?: number[]
  sheenColorMapColorSpace?: string
  sheenColorMapUsesUv2?: boolean
  sheenRoughness?: number
  sheenRoughnessMap?: Buffer
  sheenRoughnessMapWidth?: number
  sheenRoughnessMapHeight?: number
  sheenRoughnessMapWrapS?: string
  sheenRoughnessMapWrapT?: string
  sheenRoughnessMapMagFilter?: string
  sheenRoughnessMapMinFilter?: string
  sheenRoughnessMapAnisotropy?: number
  sheenRoughnessMapTransform?: number[]
  sheenRoughnessMapColorSpace?: string
  sheenRoughnessMapUsesUv2?: boolean
  anisotropy?: number
  anisotropyRotation?: number
  anisotropyMap?: Buffer
  anisotropyMapWidth?: number
  anisotropyMapHeight?: number
  anisotropyMapWrapS?: string
  anisotropyMapWrapT?: string
  anisotropyMapMagFilter?: string
  anisotropyMapMinFilter?: string
  anisotropyMapAnisotropy?: number
  anisotropyMapTransform?: number[]
  anisotropyMapColorSpace?: string
  anisotropyMapUsesUv2?: boolean
  iridescence?: number
  iridescenceMap?: Buffer
  iridescenceMapWidth?: number
  iridescenceMapHeight?: number
  iridescenceMapWrapS?: string
  iridescenceMapWrapT?: string
  iridescenceMapMagFilter?: string
  iridescenceMapMinFilter?: string
  iridescenceMapAnisotropy?: number
  iridescenceMapTransform?: number[]
  iridescenceMapColorSpace?: string
  iridescenceMapUsesUv2?: boolean
  iridescenceIor?: number
  iridescenceThicknessMin?: number
  iridescenceThicknessMax?: number
  iridescenceThicknessMap?: Buffer
  iridescenceThicknessMapWidth?: number
  iridescenceThicknessMapHeight?: number
  iridescenceThicknessMapWrapS?: string
  iridescenceThicknessMapWrapT?: string
  iridescenceThicknessMapMagFilter?: string
  iridescenceThicknessMapMinFilter?: string
  iridescenceThicknessMapAnisotropy?: number
  iridescenceThicknessMapTransform?: number[]
  iridescenceThicknessMapColorSpace?: string
  iridescenceThicknessMapUsesUv2?: boolean
  transmission?: number
  transmissionMap?: Buffer
  transmissionMapWidth?: number
  transmissionMapHeight?: number
  transmissionMapWrapS?: string
  transmissionMapWrapT?: string
  transmissionMapMagFilter?: string
  transmissionMapMinFilter?: string
  transmissionMapAnisotropy?: number
  transmissionMapTransform?: number[]
  transmissionMapColorSpace?: string
  transmissionMapUsesUv2?: boolean
  dispersion?: number
  ior?: number
  thickness?: number
  thicknessMap?: Buffer
  thicknessMapWidth?: number
  thicknessMapHeight?: number
  thicknessMapWrapS?: string
  thicknessMapWrapT?: string
  thicknessMapMagFilter?: string
  thicknessMapMinFilter?: string
  thicknessMapAnisotropy?: number
  thicknessMapTransform?: number[]
  thicknessMapColorSpace?: string
  thicknessMapUsesUv2?: boolean
  attenuationDistance?: number
  attenuationColor?: number[]
  physicalSpecularColor?: number[]
  physicalSpecularIntensity?: number
  useEnvironmentMap?: boolean
  environmentMapIntensity?: number
  environmentMapCombine?: number
  environmentMapReflectivity?: number
  environmentMapRefraction?: boolean
  environmentMapRefractionRatio?: number
  specularColorMap?: Buffer
  specularColorMapWidth?: number
  specularColorMapHeight?: number
  specularColorMapWrapS?: string
  specularColorMapWrapT?: string
  specularColorMapMagFilter?: string
  specularColorMapMinFilter?: string
  specularColorMapAnisotropy?: number
  specularColorMapTransform?: number[]
  specularColorMapColorSpace?: string
  specularColorMapUsesUv2?: boolean
  specularIntensityMap?: Buffer
  specularIntensityMapWidth?: number
  specularIntensityMapHeight?: number
  specularIntensityMapWrapS?: string
  specularIntensityMapWrapT?: string
  specularIntensityMapMagFilter?: string
  specularIntensityMapMinFilter?: string
  specularIntensityMapAnisotropy?: number
  specularIntensityMapTransform?: number[]
  specularIntensityMapColorSpace?: string
  specularIntensityMapUsesUv2?: boolean
  emissive?: number[]
  emissiveIntensity?: number
  specularColor?: number[]
  shininess?: number
  normalMap?: Buffer
  normalMapWidth?: number
  normalMapHeight?: number
  normalMapWrapS?: string
  normalMapWrapT?: string
  normalMapMagFilter?: string
  normalMapMinFilter?: string
  normalMapAnisotropy?: number
  normalMapTransform?: number[]
  normalMapColorSpace?: string
  normalMapUsesUv2?: boolean
  normalMapType?: 'tangent' | 'object'
  normalScale?: number[]
  bumpMap?: Buffer
  bumpMapWidth?: number
  bumpMapHeight?: number
  bumpMapWrapS?: string
  bumpMapWrapT?: string
  bumpMapMagFilter?: string
  bumpMapMinFilter?: string
  bumpMapAnisotropy?: number
  bumpMapTransform?: number[]
  bumpMapColorSpace?: string
  bumpMapUsesUv2?: boolean
  bumpScale?: number
  matcapMap?: Buffer
  matcapMapWidth?: number
  matcapMapHeight?: number
  matcapMapWrapS?: string
  matcapMapWrapT?: string
  matcapMapMagFilter?: string
  matcapMapMinFilter?: string
  matcapMapAnisotropy?: number
  matcapMapTransform?: number[]
  matcapMapColorSpace?: string
  matcapMapUsesUv2?: boolean
  depthPacking?: number
  distanceReferencePosition?: number[]
  distanceNear?: number
  distanceFar?: number
  gradientMap?: Buffer
  gradientMapWidth?: number
  gradientMapHeight?: number
  gradientMapWrapS?: string
  gradientMapWrapT?: string
  gradientMapMagFilter?: string
  gradientMapMinFilter?: string
  gradientMapAnisotropy?: number
  gradientMapColorSpace?: string
  displacementMap?: Buffer
  displacementMapWidth?: number
  displacementMapHeight?: number
  displacementMapWrapS?: string
  displacementMapWrapT?: string
  displacementMapMagFilter?: string
  displacementMapMinFilter?: string
  displacementMapAnisotropy?: number
  displacementMapTransform?: number[]
  displacementMapColorSpace?: string
  displacementMapUsesUv2?: boolean
  displacementScale?: number
  displacementBias?: number
  metallicRoughnessTexture?: Buffer
  metallicRoughnessTextureWidth?: number
  metallicRoughnessTextureHeight?: number
  metallicRoughnessTextureWrapS?: string
  metallicRoughnessTextureWrapT?: string
  metallicRoughnessTextureMagFilter?: string
  metallicRoughnessTextureMinFilter?: string
  metallicRoughnessTextureAnisotropy?: number
  metallicRoughnessTextureTransform?: number[]
  metallicRoughnessTextureColorSpace?: string
  metallicRoughnessTextureUsesUv2?: boolean
  emissiveMap?: Buffer
  emissiveMapWidth?: number
  emissiveMapHeight?: number
  emissiveMapWrapS?: string
  emissiveMapWrapT?: string
  emissiveMapMagFilter?: string
  emissiveMapMinFilter?: string
  emissiveMapAnisotropy?: number
  emissiveMapTransform?: number[]
  emissiveMapColorSpace?: string
  emissiveMapUsesUv2?: boolean
  aoMap?: Buffer
  aoMapWidth?: number
  aoMapHeight?: number
  aoMapWrapS?: string
  aoMapWrapT?: string
  aoMapMagFilter?: string
  aoMapMinFilter?: string
  aoMapAnisotropy?: number
  aoMapTransform?: number[]
  aoMapColorSpace?: string
  aoMapUsesUv2?: boolean
  aoMapIntensity?: number
  lightMap?: Buffer
  lightMapWidth?: number
  lightMapHeight?: number
  lightMapWrapS?: string
  lightMapWrapT?: string
  lightMapMagFilter?: string
  lightMapMinFilter?: string
  lightMapAnisotropy?: number
  lightMapTransform?: number[]
  lightMapColorSpace?: string
  lightMapUsesUv2?: boolean
  lightMapIntensity?: number
  specularMap?: Buffer
  specularMapWidth?: number
  specularMapHeight?: number
  specularMapWrapS?: string
  specularMapWrapT?: string
  specularMapMagFilter?: string
  specularMapMinFilter?: string
  specularMapAnisotropy?: number
  specularMapTransform?: number[]
  specularMapColorSpace?: string
  specularMapUsesUv2?: boolean
  alphaMap?: Buffer
  alphaMapWidth?: number
  alphaMapHeight?: number
  alphaMapWrapS?: string
  alphaMapWrapT?: string
  alphaMapMagFilter?: string
  alphaMapMinFilter?: string
  alphaMapAnisotropy?: number
  alphaMapTransform?: number[]
  alphaMapColorSpace?: string
  alphaMapUsesUv2?: boolean
  alphaTest?: number
  alphaHash?: boolean
  alphaToCoverage?: boolean
  premultipliedAlpha?: boolean
  toneMapped?: boolean
  flatShading?: boolean
  fog?: boolean
  transparent?: boolean
  blending?: string
  blendEquation?: number
  blendSrc?: number
  blendDst?: number
  blendEquationAlpha?: number
  blendSrcAlpha?: number
  blendDstAlpha?: number
  blendColor?: number[]
  blendAlpha?: number
  depthTest?: boolean
  depthFunc?: string
  depthWrite?: boolean
  colorWrite?: boolean
  polygonOffset?: boolean
  polygonOffsetFactor?: number
  polygonOffsetUnits?: number
  stencilWrite?: boolean
  stencilWriteMask?: number
  stencilFunc?: number
  stencilRef?: number
  stencilFuncMask?: number
  stencilFail?: number
  stencilZFail?: number
  stencilZPass?: number
  side?: string
  shadowSide?: string
  shadingModel?: string
  customFragmentShader?: string
}

export interface TextureInfo {
  data: Buffer
  width: number
  height: number
  wrapS?: string
  wrapT?: string
  magFilter?: string
  minFilter?: string
  anisotropy?: number
  transform?: number[]
  colorSpace?: string
  mapping?: 'uv' | 'equirectangular'
  usesUv2?: boolean
}

export interface GeometryGroup {
  start: number
  count: number
  materialIndex: number
}
