use super::SceneMesh;
use napi::bindgen_prelude::Buffer;
use napi_derive::napi;

#[napi(object)]
#[derive(Default)]
pub struct RenderScene {
    /// Output width in pixels. `camera.width` takes precedence when set.
    pub width: Option<u32>,
    /// Output height in pixels. `camera.height` takes precedence when set.
    pub height: Option<u32>,
    /// Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range.
    pub background: Option<Vec<f64>>,
    /// Background color/texture intensity multiplier. Defaults to 1.
    pub background_intensity: Option<f64>,
    /// Optional output viewport `[x, y, width, height]` in top-left pixel coordinates.
    pub viewport: Option<Vec<f64>>,
    /// Optional output scissor rectangle `[x, y, width, height]` in top-left pixel coordinates.
    pub scissor: Option<Vec<f64>>,
    /// Optional scene background texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub background_texture: Option<Buffer>,
    /// Background texture width in pixels (required when `background_texture` is raw RGBA8 bytes).
    pub background_texture_width: Option<u32>,
    /// Background texture height in pixels (required when `background_texture` is raw RGBA8 bytes).
    pub background_texture_height: Option<u32>,
    /// Background texture horizontal wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub background_texture_wrap_s: Option<String>,
    /// Background texture vertical wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`.
    pub background_texture_wrap_t: Option<String>,
    /// Background texture magnification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub background_texture_mag_filter: Option<String>,
    /// Background texture minification filter: `"nearest"` or `"linear"`. Defaults to `"linear"`.
    pub background_texture_min_filter: Option<String>,
    /// Texture anisotropy clamp requested for this sampler. Defaults to 1.
    pub background_texture_anisotropy: Option<f64>,
    /// Background texture UV transform `[a, c, tx, b, d, ty]`.
    pub background_texture_transform: Option<Vec<f64>>,
    /// Background texture color space. `"srgb"` is decoded to linear before output conversion.
    pub background_texture_color_space: Option<String>,
    /// Background texture mapping: `"uv"` (default) or `"equirectangular"`.
    pub background_texture_mapping: Option<String>,
    /// Background texture direction rotation matrix columns, flattened 3x3.
    pub background_texture_rotation: Option<Vec<f64>>,
    /// Approximate 2D background texture blur amount in the 0..1 range.
    pub background_texture_blurriness: Option<f64>,
    /// Output format. Supported values are `"png"` (default) and `"rgba"`.
    pub format: Option<String>,
    /// Output color space. Supported values are `"srgb"` (default), `"srgb-linear"`, `"linear-srgb"`, `"linearsrgb"`, and `"linear"`.
    pub output_color_space: Option<String>,
    /// Three.js tone-mapping mode. Supports No, Linear, Reinhard, Cineon, ACES Filmic, Custom, AgX, and Neutral. Defaults to ACES Filmic.
    pub tone_mapping: Option<u32>,
    /// Material tone-mapping exposure multiplier. Defaults to 1.
    pub tone_mapping_exposure: Option<f64>,
    /// Scene-color texture resolution scale for physical transmission. Defaults to 1.
    pub transmission_resolution_scale: Option<f64>,
    /// MSAA sample count. Supports `4`; omitted, `0`, or `1` use the single-sample path.
    pub sample_count: Option<u32>,
    /// Three.js shadow-map type. Supports Basic, PCF, PCFSoft, and VSM constants; defaults to PCF.
    pub shadow_map_type: Option<u32>,
    /// Triangle-list meshes generated by the JavaScript Three.js adapter.
    pub meshes: Option<Vec<SceneMesh>>,
    /// Scene lights.
    pub lights: Option<Vec<SceneLight>>,
    /// Ambient light color `[r, g, b]` in 0..1 range.
    pub ambient_light: Option<Vec<f64>>,
    /// Ambient light intensity. Defaults to 0.
    pub ambient_intensity: Option<f64>,
    /// Flattened LightProbe spherical-harmonics coefficients: 9 RGB triplets.
    pub light_probe: Option<Vec<f64>>,
    /// Optional environment map image data (equirectangular HDR/LDR, encoded or raw RGBA/Float).
    pub environment_map: Option<Buffer>,
    /// Environment map width in pixels (required when data is raw typed-array bytes).
    pub environment_map_width: Option<u32>,
    /// Environment map height in pixels (required when data is raw typed-array bytes).
    pub environment_map_height: Option<u32>,
    /// Environment map intensity multiplier. Defaults to 1.
    pub environment_map_intensity: Option<f64>,
    /// Environment map color space. `"srgb"` is decoded to linear; omitted defaults to sRGB for 8-bit inputs.
    pub environment_map_color_space: Option<String>,
    /// Environment map direction rotation matrix columns, flattened 3x3.
    pub environment_map_rotation: Option<Vec<f64>>,
    /// Scene fog mode: `"linear"` for THREE.Fog or `"exp2"` for THREE.FogExp2.
    pub fog_type: Option<String>,
    /// Fog color `[r, g, b]` in 0..1 range.
    pub fog_color: Option<Vec<f64>>,
    /// Linear fog near distance. Defaults to 1.
    pub fog_near: Option<f64>,
    /// Linear fog far distance. Defaults to 1000.
    pub fog_far: Option<f64>,
    /// Exponential squared fog density. Defaults to 0.00025.
    pub fog_density: Option<f64>,
    /// Post-processing exposure adjustment in stops. Defaults to 0.
    pub post_exposure: Option<f64>,
    /// Post-processing contrast multiplier. Defaults to 1.
    pub post_contrast: Option<f64>,
    /// Post-processing saturation multiplier. Defaults to 1.
    pub post_saturation: Option<f64>,
    /// Post-processing vignette amount 0..1. Defaults to 0.
    pub post_vignette: Option<f64>,
    /// Post-processing grayscale blend 0..1. Defaults to 0.
    pub post_grayscale: Option<f64>,
    /// Post-processing inversion blend 0..1. Defaults to 0.
    pub post_invert: Option<f64>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneLight {
    /// Light type: `"directional"`, `"point"`, `"spot"`, `"rectArea"`, or `"hemisphere"`.
    pub light_type: String,
    /// Light color `[r, g, b]` in 0..1 range.
    pub color: Option<Vec<f64>>,
    /// Light intensity.
    pub intensity: Option<f64>,
    /// World-space position `[x, y, z]` (point and spot lights).
    pub position: Option<Vec<f64>>,
    /// Direction `[x, y, z]` (directional and spot lights, up for hemisphere).
    pub direction: Option<Vec<f64>>,
    /// Maximum range. 0 = infinite (point and spot).
    pub distance: Option<f64>,
    /// Decay exponent for distance falloff (point and spot). Defaults to 2.
    pub decay: Option<f64>,
    /// Spotlight half-angle in radians. Defaults to π/3.
    pub angle: Option<f64>,
    /// Spotlight penumbra 0..1. Defaults to 0.
    pub penumbra: Option<f64>,
    /// RectAreaLight width in world units.
    pub width: Option<f64>,
    /// RectAreaLight height in world units.
    pub height: Option<f64>,
    /// Hemisphere light ground color `[r, g, b]` in 0..1 range.
    pub ground_color: Option<Vec<f64>>,
    /// Whether this light casts shadows (directional, spot, and point lights).
    pub cast_shadow: Option<bool>,
    /// Legacy square shadow map resolution in pixels. Defaults to 512 when width/height are absent.
    pub shadow_map_size: Option<u32>,
    /// Shadow map width in pixels. Defaults to `shadowMapSize` or 512.
    pub shadow_map_width: Option<u32>,
    /// Shadow map height in pixels. Defaults to `shadowMapSize` or 512.
    pub shadow_map_height: Option<u32>,
    /// Depth bias in shadow-map NDC.
    pub shadow_bias: Option<f64>,
    /// Normal-offset bias in world space at the receiver.
    pub shadow_normal_bias: Option<f64>,
    /// PCF shadow radius multiplier. Defaults to 1.
    pub shadow_radius: Option<f64>,
    /// Shadow darkness multiplier. Defaults to 1; 0 disables received shadow darkening.
    pub shadow_intensity: Option<f64>,
    /// VSM blur sample count. Defaults to Three.js' LightShadow default of 8.
    pub shadow_blur_samples: Option<f64>,
    /// Orthographic shadow-camera frustum bounds.
    pub shadow_camera_left: Option<f64>,
    pub shadow_camera_right: Option<f64>,
    pub shadow_camera_top: Option<f64>,
    pub shadow_camera_bottom: Option<f64>,
    pub shadow_camera_near: Option<f64>,
    pub shadow_camera_far: Option<f64>,
    /// Cascaded shadow split distances from the active camera.
    pub shadow_cascade_splits: Option<Vec<f64>>,
    /// Flattened cascade bounds: `[left, right, top, bottom, near, far, ...]`.
    pub shadow_cascade_bounds: Option<Vec<f64>>,
}
