/// <reference types="node" />
export declare class NativeRenderer {
  constructor()
  render(scene: RenderScene, camera: Camera): Buffer
}

export interface Camera {
  /** Output width in pixels. */
  width?: number
  /** Output height in pixels. */
  height?: number
  /** Camera position. Defaults to `[2.5, 1.8, 3.2]`. */
  eye?: Array<number>
  /** Look-at target. Defaults to `[0, 0, 0]`. */
  target?: Array<number>
  /** Up direction. Defaults to `[0, 1, 0]`. */
  up?: Array<number>
  /** Vertical field of view in degrees. Defaults to `45`. */
  fovYDegrees?: number
  /** Near clipping plane. Defaults to `0.01`. */
  near?: number
  /** Far clipping plane. Defaults to `100`. */
  far?: number
  /** Optional column-major 4x4 view-projection matrix in WebGPU clip space. */
  viewProjection?: Array<number>
  /** Camera world position `[x, y, z]` for PBR lighting. */
  cameraPosition?: Array<number>
}

export declare function renderNative(scene: RenderScene, camera: Camera): Buffer

export interface RenderScene {
  /** Output width in pixels. `camera.width` takes precedence when set. */
  width?: number
  /** Output height in pixels. `camera.height` takes precedence when set. */
  height?: number
  /** Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range. */
  background?: Array<number>
  /** Output format. Supported values are `"png"` (default) and `"rgba"`. */
  format?: string
  /** Triangle-list meshes generated by the JavaScript Three.js adapter. */
  meshes?: Array<SceneMesh>
  /** Scene lights. */
  lights?: Array<SceneLight>
  /** Ambient light color `[r, g, b]` in 0..1 range. */
  ambientLight?: Array<number>
  /** Ambient light intensity. Defaults to 0. */
  ambientIntensity?: number
  /** Optional environment map image data (equirectangular HDR/LDR, encoded or raw RGBA/Float). */
  environmentMap?: Buffer
  /** Environment map width in pixels (required when data is raw typed-array bytes). */
  environmentMapWidth?: number
  /** Environment map height in pixels (required when data is raw typed-array bytes). */
  environmentMapHeight?: number
  /** Environment map intensity multiplier. Defaults to 1. */
  environmentMapIntensity?: number
  /** Post-processing exposure adjustment in stops. Defaults to 0. */
  postExposure?: number
  /** Post-processing contrast multiplier. Defaults to 1. */
  postContrast?: number
  /** Post-processing saturation multiplier. Defaults to 1. */
  postSaturation?: number
  /** Post-processing vignette amount 0..1. Defaults to 0. */
  postVignette?: number
  /** Post-processing grayscale blend 0..1. Defaults to 0. */
  postGrayscale?: number
  /** Post-processing inversion blend 0..1. Defaults to 0. */
  postInvert?: number
}

export interface SceneLight {
  /** Light type: `"directional"`, `"point"`, `"spot"`, or `"hemisphere"`. */
  lightType: string
  /** Light color `[r, g, b]` in 0..1 range. */
  color?: Array<number>
  /** Light intensity. */
  intensity?: number
  /** World-space position `[x, y, z]` (point and spot lights). */
  position?: Array<number>
  /** Direction `[x, y, z]` (directional and spot lights, up for hemisphere). */
  direction?: Array<number>
  /** Maximum range. 0 = infinite (point and spot). */
  distance?: number
  /** Decay exponent for distance falloff (point and spot). Defaults to 2. */
  decay?: number
  /** Spotlight half-angle in radians. Defaults to π/3. */
  angle?: number
  /** Spotlight penumbra 0..1. Defaults to 0. */
  penumbra?: number
  /** Hemisphere light ground color `[r, g, b]` in 0..1 range. */
  groundColor?: Array<number>
  /** Whether this light casts shadows (directional, spot, and point lights). */
  castShadow?: boolean
  /** Shadow map resolution (square, pixels). Defaults to 512. */
  shadowMapSize?: number
  /** Depth bias in shadow-map NDC. */
  shadowBias?: number
  /** Normal-offset bias in world space at the receiver. */
  shadowNormalBias?: number
  /** Orthographic shadow-camera frustum bounds. */
  shadowCameraLeft?: number
  shadowCameraRight?: number
  shadowCameraTop?: number
  shadowCameraBottom?: number
  shadowCameraNear?: number
  shadowCameraFar?: number
  /** Cascaded shadow split distances from the active camera. */
  shadowCascadeSplits?: Array<number>
  /** Flattened cascade bounds: `[left, right, top, bottom, near, far, ...]`. */
  shadowCascadeBounds?: Array<number>
}

export interface SceneMesh {
  /** Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`. */
  positions: Array<number>
  /** Optional uint32 triangle-list indices. */
  indices?: Array<number>
  /** Optional per-vertex normals: `[nx0, ny0, nz0, ...]`. */
  normals?: Array<number>
  /** Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex. */
  colors?: Array<number>
  /** Mesh material color used when `colors` is omitted. */
  color?: Array<number>
  /** Optional column-major 4x4 model matrix. */
  transform?: Array<number>
  /** Optional per-vertex UV coordinates: `[u0, v0, u1, v1, ...]`. */
  uvs?: Array<number>
  /** Optional texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP). */
  texture?: Buffer
  /** Texture width in pixels (required when `texture` is raw RGBA8 bytes). */
  textureWidth?: number
  /** Texture height in pixels (required when `texture` is raw RGBA8 bytes). */
  textureHeight?: number
  /** Texture horizontal wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`. */
  textureWrapS?: string
  /** Texture vertical wrap mode: `"repeat"`, `"clamp"`, or `"mirror"`. Defaults to `"clamp"`. */
  textureWrapT?: string
  /** Optional metallic-roughness texture (glTF convention: G=roughness, B=metallic). */
  metallicRoughnessTexture?: Buffer
  /** Metallic-roughness texture width (required when texture is raw RGBA8 bytes). */
  metallicRoughnessTextureWidth?: number
  /** Metallic-roughness texture height (required when texture is raw RGBA8 bytes). */
  metallicRoughnessTextureHeight?: number
  /** Metallic factor (0..1). Defaults to 0. */
  metallic?: number
  /** Roughness factor (0..1). Defaults to 1. */
  roughness?: number
  /** Clearcoat intensity (0..1) for MeshPhysicalMaterial. Defaults to 0. */
  clearcoat?: number
  /** Optional clearcoat intensity map. Red channel multiplies `clearcoat`. */
  clearcoatMap?: Buffer
  /** Clearcoat map width (required when map is raw RGBA8 bytes). */
  clearcoatMapWidth?: number
  /** Clearcoat map height (required when map is raw RGBA8 bytes). */
  clearcoatMapHeight?: number
  /** Clearcoat roughness (0..1). Defaults to 0. */
  clearcoatRoughness?: number
  /** Optional clearcoat roughness map. Green channel multiplies `clearcoatRoughness`. */
  clearcoatRoughnessMap?: Buffer
  /** Clearcoat roughness map width (required when map is raw RGBA8 bytes). */
  clearcoatRoughnessMapWidth?: number
  /** Clearcoat roughness map height (required when map is raw RGBA8 bytes). */
  clearcoatRoughnessMapHeight?: number
  /** Optional clearcoat normal map. */
  clearcoatNormalMap?: Buffer
  /** Clearcoat normal map width (required when map is raw RGBA8 bytes). */
  clearcoatNormalMapWidth?: number
  /** Clearcoat normal map height (required when map is raw RGBA8 bytes). */
  clearcoatNormalMapHeight?: number
  /** Clearcoat normal map scale `[x, y]`. Defaults to `[1, 1]`. */
  clearcoatNormalScale?: Array<number>
  /** Sheen color/intensity `[r, g, b]` in 0..1 range. */
  sheenColor?: Array<number>
  /** Optional sheen color map. RGB channels multiply `sheenColor`. */
  sheenColorMap?: Buffer
  /** Sheen color map width (required when map is raw RGBA8 bytes). */
  sheenColorMapWidth?: number
  /** Sheen color map height (required when map is raw RGBA8 bytes). */
  sheenColorMapHeight?: number
  /** Sheen roughness (0..1). Defaults to 1 when sheen is present. */
  sheenRoughness?: number
  /** Optional sheen roughness map. Alpha channel multiplies `sheenRoughness`. */
  sheenRoughnessMap?: Buffer
  /** Sheen roughness map width (required when map is raw RGBA8 bytes). */
  sheenRoughnessMapWidth?: number
  /** Sheen roughness map height (required when map is raw RGBA8 bytes). */
  sheenRoughnessMapHeight?: number
  /** Anisotropy strength (0..1). Defaults to 0. */
  anisotropy?: number
  /** Anisotropy rotation in tangent space, radians. */
  anisotropyRotation?: number
  /** Optional anisotropy map. RG encode direction and B encodes strength. */
  anisotropyMap?: Buffer
  /** Anisotropy map width (required when map is raw RGBA8 bytes). */
  anisotropyMapWidth?: number
  /** Anisotropy map height (required when map is raw RGBA8 bytes). */
  anisotropyMapHeight?: number
  /** Physical transmission factor (0..1). Defaults to 0. */
  transmission?: number
  /** Optional transmission map. Red channel multiplies `transmission`. */
  transmissionMap?: Buffer
  /** Transmission map width (required when map is raw RGBA8 bytes). */
  transmissionMapWidth?: number
  /** Transmission map height (required when map is raw RGBA8 bytes). */
  transmissionMapHeight?: number
  /** Index of refraction for physical materials. Defaults to 1.5. */
  ior?: number
  /** Transmission volume thickness in model units. Defaults to 0. */
  thickness?: number
  /** Optional thickness map. Green channel multiplies `thickness`. */
  thicknessMap?: Buffer
  /** Thickness map width (required when map is raw RGBA8 bytes). */
  thicknessMapWidth?: number
  /** Thickness map height (required when map is raw RGBA8 bytes). */
  thicknessMapHeight?: number
  /** Transmission attenuation distance. Defaults to a very large distance. */
  attenuationDistance?: number
  /** Transmission attenuation color `[r, g, b]` in 0..1 range. */
  attenuationColor?: Array<number>
  /** Emissive color `[r, g, b]` in 0..1 range. */
  emissive?: Array<number>
  /** Emissive intensity multiplier. Defaults to 1. */
  emissiveIntensity?: number
  /** Optional normal map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP). */
  normalMap?: Buffer
  /** Normal map width in pixels (required when `normal_map` is raw RGBA8 bytes). */
  normalMapWidth?: number
  /** Normal map height in pixels (required when `normal_map` is raw RGBA8 bytes). */
  normalMapHeight?: number
  /** Normal map scale `[x, y]`. Defaults to `[1, 1]`. */
  normalScale?: Array<number>
  /** Optional emissive map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP). */
  emissiveMap?: Buffer
  /** Emissive map width in pixels (required when `emissive_map` is raw RGBA8 bytes). */
  emissiveMapWidth?: number
  /** Emissive map height in pixels (required when `emissive_map` is raw RGBA8 bytes). */
  emissiveMapHeight?: number
  /**
   * Optional ambient occlusion map image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
   * Red channel is used as the occlusion factor (Three.js / glTF convention).
   */
  aoMap?: Buffer
  /** AO map width in pixels (required when `ao_map` is raw RGBA8 bytes). */
  aoMapWidth?: number
  /** AO map height in pixels (required when `ao_map` is raw RGBA8 bytes). */
  aoMapHeight?: number
  /** AO map intensity multiplier (0..1). Defaults to 1. */
  aoMapIntensity?: number
  /** Alpha test cutoff threshold (0..1). Fragments with alpha below this are discarded. */
  alphaTest?: number
  /** Whether the mesh is transparent (sorted back-to-front, no depth write). */
  transparent?: boolean
  /** Which faces to render: `"front"` (default), `"back"`, or `"double"`. */
  side?: string
  /**
   * Shading model: `"standard"` (default PBR), `"basic"` (unlit / MeshBasicMaterial),
   * or `"lambert"` (diffuse-only / MeshLambertMaterial).
   */
  shadingModel?: string
  /** Primitive topology: `"triangles"` (default), `"lines"` (LineList), or `"points"`. */
  topology?: string
  /** WGSL fragment shader body for the custom material path. */
  customFragmentShader?: string
  /** Whether this mesh casts shadows in the shadow pass. Defaults to false. */
  castShadow?: boolean
  /** Whether this mesh receives shadows in the main pass. Defaults to false. */
  receiveShadow?: boolean
}
