use std::sync::OnceLock;

use anyhow::{Context, Result, anyhow, bail};
use bytemuck::{Pod, Zeroable};
use glam::{Mat4, Vec3};
use image::{ColorType, ImageEncoder, codecs::png::PngEncoder};
use napi::bindgen_prelude::Buffer;
use napi_derive::napi;
use wgpu::util::DeviceExt;

const COLOR_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba8Unorm;
const DEPTH_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Depth24Plus;
const MAX_DIMENSION: u32 = 8192;
const DEFAULT_WIDTH: u32 = 512;
const DEFAULT_HEIGHT: u32 = 512;

static SHARED_RENDERER: OnceLock<std::result::Result<GpuRenderer, String>> = OnceLock::new();

#[napi(object)]
#[derive(Default)]
pub struct RenderScene {
    /// Output width in pixels. `camera.width` takes precedence when set.
    pub width: Option<u32>,
    /// Output height in pixels. `camera.height` takes precedence when set.
    pub height: Option<u32>,
    /// Clear color as `[r, g, b]` or `[r, g, b, a]`, with values in the 0..1 range.
    pub background: Option<Vec<f64>>,
    /// Output format. Supported values are `"png"` (default) and `"rgba"`.
    pub format: Option<String>,
    /// Triangle-list meshes generated by the JavaScript Three.js adapter.
    pub meshes: Option<Vec<SceneMesh>>,
    /// Scene lights.
    pub lights: Option<Vec<SceneLight>>,
    /// Ambient light color `[r, g, b]` in 0..1 range.
    pub ambient_light: Option<Vec<f64>>,
    /// Ambient light intensity. Defaults to 0.
    pub ambient_intensity: Option<f64>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneLight {
    /// Light type: `"directional"`, `"point"`, `"spot"`, or `"hemisphere"`.
    pub light_type: String,
    /// Light color `[r, g, b]` in 0..1 range.
    pub color: Option<Vec<f64>>,
    /// Light intensity.
    pub intensity: Option<f64>,
    /// World-space position `[x, y, z]` (point and spot lights).
    pub position: Option<Vec<f64>>,
    /// Direction `[x, y, z]` (directional and spot lights, up for hemisphere).
    pub direction: Option<Vec<f64>>,
    /// Maximum range. 0 = infinite (point and spot).
    pub distance: Option<f64>,
    /// Decay exponent for distance falloff (point and spot). Defaults to 2.
    pub decay: Option<f64>,
    /// Spotlight half-angle in radians. Defaults to π/3.
    pub angle: Option<f64>,
    /// Spotlight penumbra 0..1. Defaults to 0.
    pub penumbra: Option<f64>,
    /// Hemisphere light ground color `[r, g, b]` in 0..1 range.
    pub ground_color: Option<Vec<f64>>,
}

#[napi(object)]
#[derive(Default)]
pub struct SceneMesh {
    /// Flat xyz positions: `[x0, y0, z0, x1, y1, z1, ...]`.
    pub positions: Vec<f64>,
    /// Optional uint32 triangle-list indices.
    pub indices: Option<Vec<u32>>,
    /// Optional per-vertex normals: `[nx0, ny0, nz0, ...]`.
    pub normals: Option<Vec<f64>>,
    /// Optional per-vertex colors. Accepts one `[r,g,b,a]` color or one color per vertex.
    pub colors: Option<Vec<f64>>,
    /// Mesh material color used when `colors` is omitted.
    pub color: Option<Vec<f64>>,
    /// Optional column-major 4x4 model matrix.
    pub transform: Option<Vec<f64>>,
    /// Optional per-vertex UV coordinates: `[u0, v0, u1, v1, ...]`.
    pub uvs: Option<Vec<f64>>,
    /// Optional texture image data (raw RGBA8 bytes or encoded PNG/JPEG/WebP).
    pub texture: Option<Buffer>,
    /// Texture width in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_width: Option<u32>,
    /// Texture height in pixels (required when `texture` is raw RGBA8 bytes).
    pub texture_height: Option<u32>,
    /// Metallic factor (0..1). Defaults to 0.
    pub metallic: Option<f64>,
    /// Roughness factor (0..1). Defaults to 1.
    pub roughness: Option<f64>,
    /// Emissive color `[r, g, b]` in 0..1 range.
    pub emissive: Option<Vec<f64>>,
    /// Emissive intensity multiplier. Defaults to 1.
    pub emissive_intensity: Option<f64>,
}

#[napi(object)]
#[derive(Clone, Debug, Default)]
pub struct Camera {
    /// Output width in pixels.
    pub width: Option<u32>,
    /// Output height in pixels.
    pub height: Option<u32>,
    /// Camera position. Defaults to `[2.5, 1.8, 3.2]`.
    pub eye: Option<Vec<f64>>,
    /// Look-at target. Defaults to `[0, 0, 0]`.
    pub target: Option<Vec<f64>>,
    /// Up direction. Defaults to `[0, 1, 0]`.
    pub up: Option<Vec<f64>>,
    /// Vertical field of view in degrees. Defaults to `45`.
    pub fov_y_degrees: Option<f64>,
    /// Near clipping plane. Defaults to `0.01`.
    pub near: Option<f64>,
    /// Far clipping plane. Defaults to `100`.
    pub far: Option<f64>,
    /// Optional column-major 4x4 view-projection matrix in WebGPU clip space.
    pub view_projection: Option<Vec<f64>>,
    /// Camera world position `[x, y, z]` for PBR lighting.
    pub camera_position: Option<Vec<f64>>,
}

#[napi]
pub struct NativeRenderer {
    inner: GpuRenderer,
}

#[napi]
impl NativeRenderer {
    #[napi(constructor)]
    pub fn new() -> napi::Result<Self> {
        Ok(Self {
            inner: GpuRenderer::new().map_err(to_napi_error)?,
        })
    }

    #[napi]
    pub fn render(&self, scene: RenderScene, camera: Camera) -> napi::Result<Buffer> {
        self.inner
            .render(&scene, &camera)
            .map(Buffer::from)
            .map_err(to_napi_error)
    }
}

#[napi]
pub fn render_native(scene: RenderScene, camera: Camera) -> napi::Result<Buffer> {
    let renderer = SHARED_RENDERER
        .get_or_init(|| GpuRenderer::new().map_err(|error| error.to_string()))
        .as_ref()
        .map_err(|reason| napi::Error::from_reason(reason.clone()))?;

    renderer
        .render(&scene, &camera)
        .map(Buffer::from)
        .map_err(to_napi_error)
}

fn to_napi_error(error: anyhow::Error) -> napi::Error {
    napi::Error::from_reason(error.to_string())
}

struct GpuRenderer {
    device: wgpu::Device,
    queue: wgpu::Queue,
    pipeline: wgpu::RenderPipeline,
    uniform_layout: wgpu::BindGroupLayout,
    texture_layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    default_texture_bind_group: wgpu::BindGroup,
}

impl GpuRenderer {
    fn new() -> Result<Self> {
        pollster::block_on(Self::new_async())
    }

    async fn new_async() -> Result<Self> {
        let instance =
            wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle_from_env());

        let adapter = match instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                force_fallback_adapter: false,
                compatible_surface: None,
            })
            .await
        {
            Ok(adapter) => adapter,
            Err(first_error) => instance
                .request_adapter(&wgpu::RequestAdapterOptions {
                    power_preference: wgpu::PowerPreference::None,
                    force_fallback_adapter: true,
                    compatible_surface: None,
                })
                .await
                .map_err(|fallback_error| {
                    anyhow!(
                        "failed to find a wgpu adapter: {first_error}; fallback adapter also failed: {fallback_error}"
                    )
                })?,
        };

        let required_limits = wgpu::Limits::downlevel_defaults().using_resolution(adapter.limits());
        let (device, queue) = adapter
            .request_device(&wgpu::DeviceDescriptor {
                label: Some("headless-three-renderer device"),
                required_features: wgpu::Features::empty(),
                required_limits,
                experimental_features: wgpu::ExperimentalFeatures::disabled(),
                memory_hints: wgpu::MemoryHints::Performance,
                trace: wgpu::Trace::Off,
            })
            .await
            .context("failed to create wgpu device")?;

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("headless-three-renderer shader"),
            source: wgpu::ShaderSource::Wgsl(SHADER.into()),
        });

        let uniform_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("headless-three-renderer uniform layout"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: wgpu::BufferSize::new(std::mem::size_of::<Uniforms>() as u64),
                },
                count: None,
            }],
        });

        let texture_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("headless-three-renderer texture layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        multisampled: false,
                        view_dimension: wgpu::TextureViewDimension::D2,
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
            ],
        });

        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("headless-three-renderer sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Nearest,
            ..Default::default()
        });

        let default_texture = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("headless-three-renderer default texture"),
            size: wgpu::Extent3d {
                width: 1,
                height: 1,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: COLOR_FORMAT,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
            view_formats: &[],
        });
        queue.write_texture(
            wgpu::TexelCopyTextureInfo {
                texture: &default_texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            &[255u8, 255, 255, 255],
            wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(4),
                rows_per_image: Some(1),
            },
            wgpu::Extent3d {
                width: 1,
                height: 1,
                depth_or_array_layers: 1,
            },
        );
        let default_texture_view =
            default_texture.create_view(&wgpu::TextureViewDescriptor::default());
        let default_texture_bind_group =
            device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("headless-three-renderer default texture bind group"),
                layout: &texture_layout,
                entries: &[
                    wgpu::BindGroupEntry {
                        binding: 0,
                        resource: wgpu::BindingResource::TextureView(&default_texture_view),
                    },
                    wgpu::BindGroupEntry {
                        binding: 1,
                        resource: wgpu::BindingResource::Sampler(&sampler),
                    },
                ],
            });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("headless-three-renderer pipeline layout"),
            bind_group_layouts: &[Some(&uniform_layout), Some(&texture_layout)],
            immediate_size: 0,
        });

        let color_targets = [Some(wgpu::ColorTargetState {
            format: COLOR_FORMAT,
            blend: Some(wgpu::BlendState::ALPHA_BLENDING),
            write_mask: wgpu::ColorWrites::ALL,
        })];

        let vertex_buffers = [Vertex::layout()];
        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("headless-three-renderer pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                buffers: &vertex_buffers,
            },
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None,
                unclipped_depth: false,
                polygon_mode: wgpu::PolygonMode::Fill,
                conservative: false,
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: DEPTH_FORMAT,
                depth_write_enabled: Some(true),
                depth_compare: Some(wgpu::CompareFunction::Less),
                stencil: wgpu::StencilState::default(),
                bias: wgpu::DepthBiasState::default(),
            }),
            multisample: wgpu::MultisampleState::default(),
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                targets: &color_targets,
            }),
            multiview_mask: None,
            cache: None,
        });

        Ok(Self {
            device,
            queue,
            pipeline,
            uniform_layout,
            texture_layout,
            sampler,
            default_texture_bind_group,
        })
    }

    fn render(&self, scene: &RenderScene, camera: &Camera) -> Result<Vec<u8>> {
        let settings = RenderSettings::from_scene(scene, camera, self.device.limits())?;
        let meshes = prepare_meshes(scene)?;
        let rgba = self.render_rgba(&settings, &meshes)?;

        match settings.output_format {
            OutputFormat::Png => encode_png(&rgba, settings.width, settings.height),
            OutputFormat::Rgba => Ok(rgba),
        }
    }

    fn render_rgba(&self, settings: &RenderSettings, meshes: &[PreparedMesh]) -> Result<Vec<u8>> {
        let texture_size = wgpu::Extent3d {
            width: settings.width,
            height: settings.height,
            depth_or_array_layers: 1,
        };

        let color_texture = self.device.create_texture(&wgpu::TextureDescriptor {
            label: Some("headless-three-renderer color texture"),
            size: texture_size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: COLOR_FORMAT,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC,
            view_formats: &[],
        });
        let color_view = color_texture.create_view(&wgpu::TextureViewDescriptor::default());

        let depth_texture = self.device.create_texture(&wgpu::TextureDescriptor {
            label: Some("headless-three-renderer depth texture"),
            size: texture_size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: DEPTH_FORMAT,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            view_formats: &[],
        });
        let depth_view = depth_texture.create_view(&wgpu::TextureViewDescriptor::default());

        let gpu_meshes = meshes
            .iter()
            .map(|mesh| self.upload_mesh(settings, mesh))
            .collect::<Result<Vec<_>>>()?;

        let unpadded_bytes_per_row = settings.width * 4;
        let padded_bytes_per_row =
            align_to(unpadded_bytes_per_row, wgpu::COPY_BYTES_PER_ROW_ALIGNMENT);
        let output_buffer_size = padded_bytes_per_row as u64 * settings.height as u64;
        if output_buffer_size > self.device.limits().max_buffer_size {
            bail!(
                "render output requires {} bytes, above device max_buffer_size {}",
                output_buffer_size,
                self.device.limits().max_buffer_size
            );
        }

        let output_buffer = self.device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("headless-three-renderer readback buffer"),
            size: output_buffer_size,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("headless-three-renderer render encoder"),
            });

        {
            let color_attachments = [Some(wgpu::RenderPassColorAttachment {
                view: &color_view,
                depth_slice: None,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color {
                        r: settings.background[0],
                        g: settings.background[1],
                        b: settings.background[2],
                        a: settings.background[3],
                    }),
                    store: wgpu::StoreOp::Store,
                },
            })];

            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("headless-three-renderer render pass"),
                color_attachments: &color_attachments,
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Store,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            pass.set_pipeline(&self.pipeline);
            for mesh in &gpu_meshes {
                pass.set_bind_group(0, &mesh.bind_group, &[]);
                pass.set_bind_group(1, &mesh.texture_bind_group, &[]);
                pass.set_vertex_buffer(0, mesh.vertex_buffer.slice(..));

                if let Some(index_buffer) = &mesh.index_buffer {
                    pass.set_index_buffer(index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                    pass.draw_indexed(0..mesh.index_count, 0, 0..1);
                } else {
                    pass.draw(0..mesh.vertex_count, 0..1);
                }
            }
        }

        encoder.copy_texture_to_buffer(
            wgpu::TexelCopyTextureInfo {
                texture: &color_texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            wgpu::TexelCopyBufferInfo {
                buffer: &output_buffer,
                layout: wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(padded_bytes_per_row),
                    rows_per_image: Some(settings.height),
                },
            },
            texture_size,
        );

        self.queue.submit([encoder.finish()]);

        let buffer_slice = output_buffer.slice(..);
        let (sender, receiver) = std::sync::mpsc::channel();
        buffer_slice.map_async(wgpu::MapMode::Read, move |result| {
            let _ = sender.send(result);
        });
        self.device
            .poll(wgpu::PollType::wait_indefinitely())
            .context("failed while waiting for GPU readback")?;

        receiver
            .recv()
            .context("GPU readback callback was not delivered")?
            .context("failed to map GPU readback buffer")?;

        let padded_data = buffer_slice.get_mapped_range();
        let mut rgba = vec![0; (settings.width * settings.height * 4) as usize];
        let unpadded = unpadded_bytes_per_row as usize;
        let padded = padded_bytes_per_row as usize;

        for row in 0..settings.height as usize {
            let src_start = row * padded;
            let dst_start = row * unpadded;
            rgba[dst_start..dst_start + unpadded]
                .copy_from_slice(&padded_data[src_start..src_start + unpadded]);
        }

        drop(padded_data);
        output_buffer.unmap();

        Ok(rgba)
    }

    fn upload_mesh(&self, settings: &RenderSettings, mesh: &PreparedMesh) -> Result<GpuMesh> {
        let vertex_buffer = self
            .device
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("headless-three-renderer vertex buffer"),
                contents: bytemuck::cast_slice(&mesh.vertices),
                usage: wgpu::BufferUsages::VERTEX,
            });

        let index_buffer = mesh.indices.as_ref().map(|indices| {
            self.device
                .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                    label: Some("headless-three-renderer index buffer"),
                    contents: bytemuck::cast_slice(indices),
                    usage: wgpu::BufferUsages::INDEX,
                })
        });

        let model = mesh.transform;
        let mvp = settings.view_projection * model;
        let normal_matrix = model.inverse().transpose();

        let mut lights = [GpuLight::zeroed(); MAX_LIGHTS];
        for (i, light) in settings.lights.iter().take(MAX_LIGHTS).enumerate() {
            lights[i] = *light;
        }

        let uniforms = Uniforms {
            mvp: mvp.to_cols_array_2d(),
            model: model.to_cols_array_2d(),
            normal_matrix: normal_matrix.to_cols_array_2d(),
            camera_pos: [settings.camera_pos.x, settings.camera_pos.y, settings.camera_pos.z, 0.0],
            base_color: mesh.base_color,
            emissive: [mesh.emissive[0], mesh.emissive[1], mesh.emissive[2], 0.0],
            metallic: mesh.metallic,
            roughness: mesh.roughness,
            ambient_intensity: settings.ambient_intensity,
            num_lights: settings.lights.len().min(MAX_LIGHTS) as u32,
            ambient_color: [settings.ambient_color[0], settings.ambient_color[1], settings.ambient_color[2], 0.0],
            lights,
        };
        let uniform_buffer = self
            .device
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("headless-three-renderer uniform buffer"),
                contents: bytemuck::bytes_of(&uniforms),
                usage: wgpu::BufferUsages::UNIFORM,
            });

        let bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("headless-three-renderer bind group"),
            layout: &self.uniform_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: uniform_buffer.as_entire_binding(),
            }],
        });

        let (texture_bind_group, _mesh_texture) = match &mesh.texture {
            Some(tex) => {
                let tex_size = wgpu::Extent3d {
                    width: tex.width,
                    height: tex.height,
                    depth_or_array_layers: 1,
                };
                let gpu_texture = self.device.create_texture(&wgpu::TextureDescriptor {
                    label: Some("headless-three-renderer mesh texture"),
                    size: tex_size,
                    mip_level_count: 1,
                    sample_count: 1,
                    dimension: wgpu::TextureDimension::D2,
                    format: COLOR_FORMAT,
                    usage: wgpu::TextureUsages::TEXTURE_BINDING
                        | wgpu::TextureUsages::COPY_DST,
                    view_formats: &[],
                });
                self.queue.write_texture(
                    wgpu::TexelCopyTextureInfo {
                        texture: &gpu_texture,
                        mip_level: 0,
                        origin: wgpu::Origin3d::ZERO,
                        aspect: wgpu::TextureAspect::All,
                    },
                    &tex.rgba,
                    wgpu::TexelCopyBufferLayout {
                        offset: 0,
                        bytes_per_row: Some(4 * tex.width),
                        rows_per_image: Some(tex.height),
                    },
                    tex_size,
                );
                let tex_view =
                    gpu_texture.create_view(&wgpu::TextureViewDescriptor::default());
                let tex_bind_group =
                    self.device.create_bind_group(&wgpu::BindGroupDescriptor {
                        label: Some("headless-three-renderer mesh texture bind group"),
                        layout: &self.texture_layout,
                        entries: &[
                            wgpu::BindGroupEntry {
                                binding: 0,
                                resource: wgpu::BindingResource::TextureView(&tex_view),
                            },
                            wgpu::BindGroupEntry {
                                binding: 1,
                                resource: wgpu::BindingResource::Sampler(&self.sampler),
                            },
                        ],
                    });
                (tex_bind_group, Some(gpu_texture))
            }
            None => (self.default_texture_bind_group.clone(), None),
        };

        Ok(GpuMesh {
            vertex_buffer,
            index_buffer,
            bind_group,
            texture_bind_group,
            index_count: mesh
                .indices
                .as_ref()
                .map_or(0, |indices| indices.len() as u32),
            vertex_count: mesh.vertices.len() as u32,
            _uniform_buffer: uniform_buffer,
            _texture: _mesh_texture,
        })
    }
}

struct GpuMesh {
    vertex_buffer: wgpu::Buffer,
    index_buffer: Option<wgpu::Buffer>,
    bind_group: wgpu::BindGroup,
    texture_bind_group: wgpu::BindGroup,
    index_count: u32,
    vertex_count: u32,
    _uniform_buffer: wgpu::Buffer,
    _texture: Option<wgpu::Texture>,
}

struct RenderSettings {
    width: u32,
    height: u32,
    background: [f64; 4],
    output_format: OutputFormat,
    view_projection: Mat4,
    camera_pos: Vec3,
    lights: Vec<GpuLight>,
    ambient_color: [f32; 3],
    ambient_intensity: f32,
}

impl RenderSettings {
    fn from_scene(scene: &RenderScene, camera: &Camera, limits: wgpu::Limits) -> Result<Self> {
        let width = camera.width.or(scene.width).unwrap_or(DEFAULT_WIDTH);
        let height = camera.height.or(scene.height).unwrap_or(DEFAULT_HEIGHT);

        validate_dimension("width", width, limits.max_texture_dimension_2d)?;
        validate_dimension("height", height, limits.max_texture_dimension_2d)?;

        let background = parse_color(
            scene.background.as_deref(),
            [0.04, 0.045, 0.05, 1.0],
            "scene.background",
        )?;

        let eye = parse_vec3(camera.eye.as_deref(), [2.5, 1.8, 3.2], "camera.eye")?;
        let target = parse_vec3(camera.target.as_deref(), [0.0, 0.0, 0.0], "camera.target")?;
        let up = parse_vec3(camera.up.as_deref(), [0.0, 1.0, 0.0], "camera.up")?;

        if eye.distance_squared(target) <= f32::EPSILON {
            bail!("camera.eye must not equal camera.target");
        }
        if up.length_squared() <= f32::EPSILON {
            bail!("camera.up must not be a zero vector");
        }

        let fov_y_degrees = camera.fov_y_degrees.unwrap_or(45.0);
        if !fov_y_degrees.is_finite() || !(1.0..179.0).contains(&fov_y_degrees) {
            bail!("camera.fov_y_degrees must be finite and between 1 and 179");
        }

        let near = finite_positive(camera.near.unwrap_or(0.01), "camera.near")?;
        let far = finite_positive(camera.far.unwrap_or(100.0), "camera.far")?;
        if far <= near {
            bail!("camera.far must be greater than camera.near");
        }

        let view_projection = match camera.view_projection.as_deref() {
            Some(matrix) => parse_mat4(matrix, "camera.viewProjection")?,
            None => {
                let aspect = width as f32 / height as f32;
                let projection =
                    Mat4::perspective_rh(fov_y_degrees.to_radians() as f32, aspect, near, far);
                let view = Mat4::look_at_rh(eye, target, up.normalize());
                projection * view
            }
        };

        let camera_pos = parse_vec3(
            camera.camera_position.as_deref(),
            eye.to_array(),
            "camera.cameraPosition",
        )?;

        let output_format = OutputFormat::from_scene(scene)?;
        let lights = prepare_lights(scene)?;
        let ambient_color = parse_color(
            scene.ambient_light.as_deref(),
            [1.0, 1.0, 1.0, 1.0],
            "scene.ambientLight",
        )?;
        let ambient_intensity = scene.ambient_intensity.unwrap_or(0.0) as f32;

        Ok(Self {
            width,
            height,
            background,
            output_format,
            view_projection,
            camera_pos,
            lights,
            ambient_color: [ambient_color[0] as f32, ambient_color[1] as f32, ambient_color[2] as f32],
            ambient_intensity,
        })
    }
}

#[derive(Copy, Clone)]
enum OutputFormat {
    Png,
    Rgba,
}

impl OutputFormat {
    fn from_scene(scene: &RenderScene) -> Result<Self> {
        let Some(format) = scene.format.as_deref() else {
            return Ok(Self::Png);
        };

        match format.to_ascii_lowercase().as_str() {
            "png" => Ok(Self::Png),
            "rgba" | "raw" | "raw-rgba" => Ok(Self::Rgba),
            other => bail!("unsupported scene.format `{other}`; expected `png` or `rgba`"),
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
    color: [f32; 4],
    uv: [f32; 2],
}

impl Vertex {
    const ATTRIBUTES: [wgpu::VertexAttribute; 4] = wgpu::vertex_attr_array![
        0 => Float32x3,
        1 => Float32x3,
        2 => Float32x4,
        3 => Float32x2,
    ];

    fn layout() -> wgpu::VertexBufferLayout<'static> {
        wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<Self>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &Self::ATTRIBUTES,
        }
    }
}

const MAX_LIGHTS: usize = 16;

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct Uniforms {
    mvp: [[f32; 4]; 4],
    model: [[f32; 4]; 4],
    normal_matrix: [[f32; 4]; 4],
    camera_pos: [f32; 4],
    base_color: [f32; 4],
    emissive: [f32; 4],
    metallic: f32,
    roughness: f32,
    ambient_intensity: f32,
    num_lights: u32,
    ambient_color: [f32; 4],
    lights: [GpuLight; MAX_LIGHTS],
}

#[repr(C)]
#[derive(Copy, Clone, Pod, Zeroable)]
struct GpuLight {
    /// 0 = directional, 1 = point, 2 = spot, 3 = hemisphere
    light_type: u32,
    _pad0: [u32; 3],
    color_intensity: [f32; 4],
    /// xyz = position (point/spot) or ground_color (hemisphere), w = distance
    position: [f32; 4],
    /// xyz = direction, w = decay
    direction: [f32; 4],
    /// spot: [cos_outer_angle, cos_inner_angle, 0, 0]
    params: [f32; 4],
}

struct PreparedMesh {
    vertices: Vec<Vertex>,
    indices: Option<Vec<u32>>,
    transform: Mat4,
    texture: Option<PreparedTexture>,
    metallic: f32,
    roughness: f32,
    emissive: [f32; 3],
    base_color: [f32; 4],
}

struct PreparedTexture {
    rgba: Vec<u8>,
    width: u32,
    height: u32,
}

fn prepare_lights(scene: &RenderScene) -> Result<Vec<GpuLight>> {
    let Some(lights) = scene.lights.as_deref() else {
        return Ok(Vec::new());
    };

    let mut gpu_lights = Vec::with_capacity(lights.len().min(MAX_LIGHTS));
    for (i, light) in lights.iter().take(MAX_LIGHTS).enumerate() {
        let light_type = match light.light_type.to_ascii_lowercase().as_str() {
            "directional" => 0u32,
            "point" => 1,
            "spot" => 2,
            "hemisphere" => 3,
            other => bail!("scene.lights[{i}].lightType `{other}` is not supported"),
        };
        let color = parse_color(
            light.color.as_deref(),
            [1.0, 1.0, 1.0, 1.0],
            &format!("scene.lights[{i}].color"),
        )?;
        let intensity = light.intensity.unwrap_or(1.0) as f32;

        let distance = light.distance.unwrap_or(0.0).max(0.0) as f32;
        let decay = light.decay.unwrap_or(2.0) as f32;

        let position = if light_type == 3 {
            // Hemisphere: pack ground color into position.xyz
            let ground = parse_color(
                light.ground_color.as_deref(),
                [0.04, 0.02, 0.0, 1.0],
                &format!("scene.lights[{i}].groundColor"),
            )?;
            [ground[0] as f32, ground[1] as f32, ground[2] as f32, 0.0]
        } else {
            let pos = parse_vec3(
                light.position.as_deref(),
                [0.0, 0.0, 0.0],
                &format!("scene.lights[{i}].position"),
            )?;
            [pos.x, pos.y, pos.z, distance]
        };

        let direction = parse_vec3(
            light.direction.as_deref(),
            if light_type == 3 { [0.0, 1.0, 0.0] } else { [0.0, -1.0, 0.0] },
            &format!("scene.lights[{i}].direction"),
        )?;

        // Spot light cone parameters
        let params = if light_type == 2 {
            let angle = light.angle.unwrap_or(std::f64::consts::FRAC_PI_3).clamp(0.0, std::f64::consts::FRAC_PI_2) as f32;
            let penumbra = light.penumbra.unwrap_or(0.0).clamp(0.0, 1.0) as f32;
            let cos_outer = angle.cos();
            let cos_inner = (angle * (1.0 - penumbra)).cos();
            [cos_outer, cos_inner, 0.0, 0.0]
        } else {
            [0.0; 4]
        };

        gpu_lights.push(GpuLight {
            light_type,
            _pad0: [0; 3],
            color_intensity: [color[0] as f32, color[1] as f32, color[2] as f32, intensity],
            position,
            direction: [direction.x, direction.y, direction.z, decay],
            params,
        });
    }
    Ok(gpu_lights)
}

fn prepare_meshes(scene: &RenderScene) -> Result<Vec<PreparedMesh>> {
    if let Some(meshes) = scene.meshes.as_deref() {
        meshes.iter().enumerate().map(prepare_mesh).collect()
    } else {
        Ok(Vec::new())
    }
}

fn prepare_mesh((mesh_index, mesh): (usize, &SceneMesh)) -> Result<PreparedMesh> {
    if mesh.positions.len() < 9 || mesh.positions.len() % 3 != 0 {
        bail!("scene.meshes[{mesh_index}].positions must contain at least 3 xyz vertices");
    }

    let vertex_count = mesh.positions.len() / 3;
    let material_color = parse_color(
        mesh.color.as_deref(),
        [0.82, 0.82, 0.82, 1.0],
        &format!("scene.meshes[{mesh_index}].color"),
    )?;

    let color_mode = ColorMode::new(
        mesh.colors.as_deref(),
        vertex_count,
        material_color,
        mesh_index,
    )?;

    let uvs = mesh.uvs.as_deref();
    let has_uvs = uvs.map_or(false, |u| u.len() == vertex_count * 2);
    if let Some(u) = uvs {
        if u.len() != vertex_count * 2 {
            bail!(
                "scene.meshes[{mesh_index}].uvs has length {}; expected {}",
                u.len(),
                vertex_count * 2,
            );
        }
    }

    let normals = mesh.normals.as_deref();
    let has_normals = normals.map_or(false, |n| n.len() == vertex_count * 3);
    if let Some(n) = normals {
        if n.len() != vertex_count * 3 {
            bail!(
                "scene.meshes[{mesh_index}].normals has length {}; expected {}",
                n.len(),
                vertex_count * 3,
            );
        }
    }

    let mut vertices = Vec::with_capacity(vertex_count);
    for vertex_index in 0..vertex_count {
        let base = vertex_index * 3;
        let uv_base = vertex_index * 2;
        vertices.push(Vertex {
            position: [
                finite_f32(mesh.positions[base], "mesh position")?,
                finite_f32(mesh.positions[base + 1], "mesh position")?,
                finite_f32(mesh.positions[base + 2], "mesh position")?,
            ],
            normal: if has_normals {
                let n = normals.unwrap();
                [n[base] as f32, n[base + 1] as f32, n[base + 2] as f32]
            } else {
                [0.0, 0.0, 0.0]
            },
            color: color_mode.color(vertex_index),
            uv: if has_uvs {
                let u = uvs.unwrap();
                [u[uv_base] as f32, u[uv_base + 1] as f32]
            } else {
                [0.0, 0.0]
            },
        });
    }

    // If no normals were provided, compute flat normals from triangle faces
    if !has_normals {
        compute_flat_normals(&mut vertices, mesh.indices.as_deref());
    }

    let indices = match &mesh.indices {
        Some(indices) => {
            if indices.len() < 3 || indices.len() % 3 != 0 {
                bail!("scene.meshes[{mesh_index}].indices must contain triangle-list indices");
            }
            for &index in indices {
                if index as usize >= vertex_count {
                    bail!("scene.meshes[{mesh_index}].indices contains out-of-range index {index}");
                }
            }
            Some(indices.clone())
        }
        None => {
            if vertex_count % 3 != 0 {
                bail!(
                    "scene.meshes[{mesh_index}] has no indices, so positions must define complete triangles"
                );
            }
            None
        }
    };

    let texture = match &mesh.texture {
        Some(tex_data) if !tex_data.is_empty() => Some(decode_texture(
            tex_data,
            mesh.texture_width,
            mesh.texture_height,
            mesh_index,
        )?),
        _ => None,
    };

    let metallic = clamp01(mesh.metallic.unwrap_or(0.0)) as f32;
    let roughness = clamp01(mesh.roughness.unwrap_or(1.0)) as f32;
    let emissive_intensity = mesh.emissive_intensity.unwrap_or(1.0) as f32;
    let emissive = match mesh.emissive.as_deref() {
        Some(e) if e.len() == 3 => [
            clamp01(e[0]) as f32 * emissive_intensity,
            clamp01(e[1]) as f32 * emissive_intensity,
            clamp01(e[2]) as f32 * emissive_intensity,
        ],
        _ => [0.0, 0.0, 0.0],
    };

    Ok(PreparedMesh {
        vertices,
        indices,
        transform: parse_transform(mesh.transform.as_deref(), mesh_index)?,
        texture,
        metallic,
        roughness,
        emissive,
        base_color: color_to_f32(material_color),
    })
}

fn decode_texture(
    data: &[u8],
    width_hint: Option<u32>,
    height_hint: Option<u32>,
    mesh_index: usize,
) -> Result<PreparedTexture> {
    let w = width_hint.unwrap_or(0);
    let h = height_hint.unwrap_or(0);

    if w > 0 && h > 0 && data.len() == (w as usize) * (h as usize) * 4 {
        return Ok(PreparedTexture {
            rgba: data.to_vec(),
            width: w,
            height: h,
        });
    }

    let img = image::load_from_memory(data).with_context(|| {
        format!("scene.meshes[{mesh_index}].texture: failed to decode image ({} bytes)", data.len())
    })?;
    let rgba = img.to_rgba8();
    Ok(PreparedTexture {
        width: rgba.width(),
        height: rgba.height(),
        rgba: rgba.into_raw(),
    })
}

enum ColorMode<'a> {
    Uniform([f32; 4]),
    RgbPerVertex(&'a [f64]),
    RgbaPerVertex(&'a [f64]),
}

impl<'a> ColorMode<'a> {
    fn new(
        colors: Option<&'a [f64]>,
        vertex_count: usize,
        material_color: [f64; 4],
        mesh_index: usize,
    ) -> Result<Self> {
        let Some(colors) = colors else {
            return Ok(Self::Uniform(color_to_f32(material_color)));
        };

        match colors.len() {
            3 | 4 => Ok(Self::Uniform(color_to_f32(parse_color(
                Some(colors),
                material_color,
                &format!("scene.meshes[{mesh_index}].colors"),
            )?))),
            len if len == vertex_count * 3 => Ok(Self::RgbPerVertex(colors)),
            len if len == vertex_count * 4 => Ok(Self::RgbaPerVertex(colors)),
            len => bail!(
                "scene.meshes[{mesh_index}].colors has length {len}; expected 3, 4, vertex_count * 3, or vertex_count * 4"
            ),
        }
    }

    fn color(&self, vertex_index: usize) -> [f32; 4] {
        match self {
            Self::Uniform(color) => *color,
            Self::RgbPerVertex(colors) => {
                let base = vertex_index * 3;
                [
                    clamp01(colors[base]) as f32,
                    clamp01(colors[base + 1]) as f32,
                    clamp01(colors[base + 2]) as f32,
                    1.0,
                ]
            }
            Self::RgbaPerVertex(colors) => {
                let base = vertex_index * 4;
                [
                    clamp01(colors[base]) as f32,
                    clamp01(colors[base + 1]) as f32,
                    clamp01(colors[base + 2]) as f32,
                    clamp01(colors[base + 3]) as f32,
                ]
            }
        }
    }
}

fn parse_vec3(values: Option<&[f64]>, default: [f32; 3], field: &str) -> Result<Vec3> {
    let Some(values) = values else {
        return Ok(Vec3::from_array(default));
    };

    if values.len() != 3 {
        bail!("{field} must be an array of 3 numbers");
    }

    Ok(Vec3::new(
        finite_f32(values[0], field)?,
        finite_f32(values[1], field)?,
        finite_f32(values[2], field)?,
    ))
}

fn parse_color(values: Option<&[f64]>, default: [f64; 4], field: &str) -> Result<[f64; 4]> {
    let Some(values) = values else {
        return Ok(default);
    };

    match values.len() {
        3 => Ok([
            finite_color(values[0], field)?,
            finite_color(values[1], field)?,
            finite_color(values[2], field)?,
            default[3],
        ]),
        4 => Ok([
            finite_color(values[0], field)?,
            finite_color(values[1], field)?,
            finite_color(values[2], field)?,
            finite_color(values[3], field)?,
        ]),
        _ => bail!("{field} must be `[r, g, b]` or `[r, g, b, a]`"),
    }
}

fn parse_transform(values: Option<&[f64]>, mesh_index: usize) -> Result<Mat4> {
    let Some(values) = values else {
        return Ok(Mat4::IDENTITY);
    };

    parse_mat4(values, &format!("scene.meshes[{mesh_index}].transform"))
}

fn parse_mat4(values: &[f64], field: &str) -> Result<Mat4> {
    if values.len() != 16 {
        bail!("{field} must be a column-major 4x4 matrix");
    }
    let mut matrix = [0.0; 16];
    for (slot, value) in matrix.iter_mut().zip(values) {
        *slot = finite_f32(*value, field)?;
    }

    Ok(Mat4::from_cols_array(&matrix))
}

fn finite_positive(value: f64, field: &str) -> Result<f32> {
    let value = finite_f32(value, field)?;
    if value <= 0.0 {
        bail!("{field} must be greater than 0");
    }
    Ok(value)
}

fn finite_f32(value: f64, field: &str) -> Result<f32> {
    if !value.is_finite() || value < f32::MIN as f64 || value > f32::MAX as f64 {
        bail!("{field} must contain finite f32-compatible numbers");
    }
    Ok(value as f32)
}

fn finite_color(value: f64, field: &str) -> Result<f64> {
    if !value.is_finite() {
        bail!("{field} must contain finite numbers");
    }
    Ok(clamp01(value))
}

fn color_to_f32(color: [f64; 4]) -> [f32; 4] {
    [
        color[0] as f32,
        color[1] as f32,
        color[2] as f32,
        color[3] as f32,
    ]
}

fn clamp01(value: f64) -> f64 {
    value.clamp(0.0, 1.0)
}

fn validate_dimension(name: &str, value: u32, device_limit: u32) -> Result<()> {
    if value == 0 {
        bail!("{name} must be greater than 0");
    }
    if value > MAX_DIMENSION {
        bail!("{name} must be <= {MAX_DIMENSION}");
    }
    if value > device_limit {
        bail!("{name} {value} exceeds the selected GPU limit {device_limit}");
    }
    Ok(())
}

fn align_to(value: u32, alignment: u32) -> u32 {
    value.div_ceil(alignment) * alignment
}

fn encode_png(rgba: &[u8], width: u32, height: u32) -> Result<Vec<u8>> {
    let mut png = Vec::new();
    PngEncoder::new(&mut png)
        .write_image(rgba, width, height, ColorType::Rgba8.into())
        .context("failed to encode PNG")?;
    Ok(png)
}

fn compute_flat_normals(vertices: &mut [Vertex], indices: Option<&[u32]>) {
    match indices {
        Some(idx) => {
            for tri in idx.chunks_exact(3) {
                let (i0, i1, i2) = (tri[0] as usize, tri[1] as usize, tri[2] as usize);
                let p0 = Vec3::from(vertices[i0].position);
                let p1 = Vec3::from(vertices[i1].position);
                let p2 = Vec3::from(vertices[i2].position);
                let normal = (p1 - p0).cross(p2 - p0);
                let n = if normal.length_squared() > 0.0 {
                    normal.normalize()
                } else {
                    Vec3::Y
                };
                let arr = n.to_array();
                // Accumulate for shared vertices
                for &vi in &[i0, i1, i2] {
                    vertices[vi].normal[0] += arr[0];
                    vertices[vi].normal[1] += arr[1];
                    vertices[vi].normal[2] += arr[2];
                }
            }
            // Normalize accumulated
            for v in vertices.iter_mut() {
                let n = Vec3::from(v.normal);
                if n.length_squared() > 0.0 {
                    v.normal = n.normalize().to_array();
                } else {
                    v.normal = [0.0, 1.0, 0.0];
                }
            }
        }
        None => {
            for tri in vertices.chunks_exact_mut(3) {
                let p0 = Vec3::from(tri[0].position);
                let p1 = Vec3::from(tri[1].position);
                let p2 = Vec3::from(tri[2].position);
                let normal = (p1 - p0).cross(p2 - p0);
                let n = if normal.length_squared() > 0.0 {
                    normal.normalize()
                } else {
                    Vec3::Y
                };
                let arr = n.to_array();
                tri[0].normal = arr;
                tri[1].normal = arr;
                tri[2].normal = arr;
            }
        }
    }
}

const SHADER: &str = r#"
const PI: f32 = 3.14159265359;
const MAX_LIGHTS: u32 = 16u;

struct GpuLight {
  light_type: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  color_intensity: vec4<f32>,
  // xyz = position (point/spot) or ground_color (hemisphere), w = distance
  position: vec4<f32>,
  // xyz = direction, w = decay
  direction: vec4<f32>,
  // spot: x = cos(outer_angle), y = cos(inner_angle)
  params: vec4<f32>,
};

struct Uniforms {
  mvp: mat4x4<f32>,
  model: mat4x4<f32>,
  normal_matrix: mat4x4<f32>,
  camera_pos: vec4<f32>,
  base_color: vec4<f32>,
  emissive: vec4<f32>,
  metallic: f32,
  roughness: f32,
  ambient_intensity: f32,
  num_lights: u32,
  ambient_color: vec4<f32>,
  lights: array<GpuLight, 16>,
};

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;

@group(1) @binding(0)
var t_diffuse: texture_2d<f32>;
@group(1) @binding(1)
var s_diffuse: sampler;

struct VertexInput {
  @location(0) position: vec3<f32>,
  @location(1) normal: vec3<f32>,
  @location(2) color: vec4<f32>,
  @location(3) uv: vec2<f32>,
};

struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) world_pos: vec3<f32>,
  @location(1) world_normal: vec3<f32>,
  @location(2) color: vec4<f32>,
  @location(3) uv: vec2<f32>,
};

@vertex
fn vs_main(input: VertexInput) -> VertexOutput {
  var output: VertexOutput;
  let world_pos = uniforms.model * vec4<f32>(input.position, 1.0);
  output.position = uniforms.mvp * vec4<f32>(input.position, 1.0);
  output.world_pos = world_pos.xyz;
  output.world_normal = normalize((uniforms.normal_matrix * vec4<f32>(input.normal, 0.0)).xyz);
  output.color = input.color;
  output.uv = input.uv;
  return output;
}

// GGX/Trowbridge-Reitz normal distribution
fn distribution_ggx(n_dot_h: f32, roughness: f32) -> f32 {
  let a = roughness * roughness;
  let a2 = a * a;
  let d = n_dot_h * n_dot_h * (a2 - 1.0) + 1.0;
  return a2 / (PI * d * d + 0.0001);
}

// Schlick-GGX geometry function
fn geometry_schlick_ggx(n_dot_v: f32, roughness: f32) -> f32 {
  let r = roughness + 1.0;
  let k = (r * r) / 8.0;
  return n_dot_v / (n_dot_v * (1.0 - k) + k + 0.0001);
}

fn geometry_smith(n_dot_v: f32, n_dot_l: f32, roughness: f32) -> f32 {
  return geometry_schlick_ggx(n_dot_v, roughness) * geometry_schlick_ggx(n_dot_l, roughness);
}

// Schlick Fresnel approximation
fn fresnel_schlick(cos_theta: f32, f0: vec3<f32>) -> vec3<f32> {
  return f0 + (vec3<f32>(1.0) - f0) * pow(clamp(1.0 - cos_theta, 0.0, 1.0), 5.0);
}

// Three.js-compatible distance attenuation
// distance = cutoff distance (0 = infinite range)
// decay = decay exponent (default 2, physically correct)
fn get_distance_attenuation(light_distance: f32, cutoff_distance: f32, decay_exponent: f32) -> f32 {
  var falloff = 1.0 / max(pow(light_distance, decay_exponent), 0.01);
  if cutoff_distance > 0.0 {
    let ratio = light_distance / cutoff_distance;
    let ratio2 = ratio * ratio;
    let ratio4 = ratio2 * ratio2;
    let window = saturate(1.0 - ratio4);
    falloff *= window * window;
  }
  return falloff;
}

// Three.js-compatible spot attenuation
fn get_spot_attenuation(cone_cos: f32, penumbra_cos: f32, angle_cos: f32) -> f32 {
  return smoothstep(cone_cos, penumbra_cos, angle_cos);
}

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
  let uv = vec2<f32>(input.uv.x, 1.0 - input.uv.y);
  let tex_color = textureSample(t_diffuse, s_diffuse, uv);
  let albedo = tex_color.rgb * input.color.rgb * uniforms.base_color.rgb;
  let alpha = tex_color.a * input.color.a * uniforms.base_color.a;

  let metallic = uniforms.metallic;
  let roughness = max(uniforms.roughness, 0.04);

  let N = normalize(input.world_normal);
  let V = normalize(uniforms.camera_pos.xyz - input.world_pos);
  let n_dot_v = max(dot(N, V), 0.0);

  // Dielectric F0 = 0.04, metallic F0 = albedo
  let f0 = mix(vec3<f32>(0.04), albedo, metallic);

  var lo = vec3<f32>(0.0);

  if uniforms.num_lights == 0u {
    // No lights: render with a basic hemispherical ambient
    let ambient = uniforms.ambient_color.rgb * uniforms.ambient_intensity;
    let sky_factor = 0.5 + 0.5 * N.y;
    let fallback_ambient = mix(vec3<f32>(0.1, 0.1, 0.12), vec3<f32>(0.4, 0.45, 0.5), sky_factor);
    let total_ambient = max(ambient, fallback_ambient);
    lo = albedo * total_ambient;
  } else {
    for (var i = 0u; i < uniforms.num_lights && i < MAX_LIGHTS; i = i + 1u) {
      let light = uniforms.lights[i];

      if light.light_type == 3u {
        // Hemisphere light
        let up = normalize(light.direction.xyz);
        let sky_color = light.color_intensity.rgb * light.color_intensity.w;
        let ground_color = light.position.xyz * light.color_intensity.w;
        let hemi_factor = 0.5 + 0.5 * dot(N, up);
        lo = lo + albedo * mix(ground_color, sky_color, hemi_factor);
        continue;
      }

      var L: vec3<f32>;
      var attenuation: f32 = 1.0;

      if light.light_type == 0u {
        // Directional
        L = normalize(-light.direction.xyz);
      } else {
        // Point or Spot
        let light_vec = light.position.xyz - input.world_pos;
        let dist = length(light_vec);
        L = light_vec / max(dist, 0.0001);
        let cutoff_distance = light.position.w;
        let decay_exponent = light.direction.w;
        attenuation = get_distance_attenuation(dist, cutoff_distance, decay_exponent);

        // Spot cone attenuation
        if light.light_type == 2u {
          let cos_angle = dot(normalize(-light_vec), normalize(light.direction.xyz));
          let cone_cos = light.params.x;
          let penumbra_cos = light.params.y;
          attenuation *= get_spot_attenuation(cone_cos, penumbra_cos, cos_angle);
        }
      }

      let H = normalize(V + L);
      let n_dot_l = max(dot(N, L), 0.0);
      let n_dot_h = max(dot(N, H), 0.0);
      let h_dot_v = max(dot(H, V), 0.0);

      // Cook-Torrance BRDF
      let D = distribution_ggx(n_dot_h, roughness);
      let G = geometry_smith(n_dot_v, n_dot_l, roughness);
      let F = fresnel_schlick(h_dot_v, f0);

      let specular = (D * G * F) / (4.0 * n_dot_v * n_dot_l + 0.0001);

      let k_s = F;
      let k_d = (vec3<f32>(1.0) - k_s) * (1.0 - metallic);

      let radiance = light.color_intensity.rgb * light.color_intensity.w * attenuation;
      lo = lo + (k_d * albedo / PI + specular) * radiance * n_dot_l;
    }

    // Ambient
    let ambient = uniforms.ambient_color.rgb * uniforms.ambient_intensity * albedo;
    lo = lo + ambient;
  }

  // Emissive
  lo = lo + uniforms.emissive.rgb;

  // Tone mapping (Reinhard) and gamma correction
  let mapped = lo / (lo + vec3<f32>(1.0));
  let gamma_corrected = pow(mapped, vec3<f32>(1.0 / 2.2));

  return vec4<f32>(gamma_corrected, alpha);
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_scene_prepares_no_meshes() {
        let scene = RenderScene::default();
        let meshes = prepare_meshes(&scene).unwrap();
        assert!(meshes.is_empty());
    }

    #[test]
    fn rejects_non_triangle_unindexed_mesh() {
        let scene = RenderScene {
            meshes: Some(vec![SceneMesh {
                positions: vec![0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
                ..SceneMesh::default()
            }]),
            ..RenderScene::default()
        };

        assert!(prepare_meshes(&scene).is_err());
    }

    #[test]
    fn accepts_indexed_quad() {
        let scene = RenderScene {
            meshes: Some(vec![SceneMesh {
                positions: vec![0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
                indices: Some(vec![0, 1, 2, 0, 2, 3]),
                color: Some(vec![1.0, 0.0, 0.0, 1.0]),
                ..SceneMesh::default()
            }]),
            ..RenderScene::default()
        };

        let meshes = prepare_meshes(&scene).unwrap();
        assert_eq!(meshes[0].vertices.len(), 4);
        assert_eq!(meshes[0].indices.as_ref().unwrap().len(), 6);
    }

    #[test]
    fn accepts_mesh_with_uvs() {
        let scene = RenderScene {
            meshes: Some(vec![SceneMesh {
                positions: vec![0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                uvs: Some(vec![0.0, 0.0, 1.0, 0.0, 0.0, 1.0]),
                ..SceneMesh::default()
            }]),
            ..RenderScene::default()
        };

        let meshes = prepare_meshes(&scene).unwrap();
        assert_eq!(meshes[0].vertices[0].uv, [0.0, 0.0]);
        assert_eq!(meshes[0].vertices[1].uv, [1.0, 0.0]);
        assert_eq!(meshes[0].vertices[2].uv, [0.0, 1.0]);
    }

    #[test]
    fn rejects_bad_uv_length() {
        let scene = RenderScene {
            meshes: Some(vec![SceneMesh {
                positions: vec![0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                uvs: Some(vec![0.0, 0.0, 1.0]), // wrong length
                ..SceneMesh::default()
            }]),
            ..RenderScene::default()
        };

        assert!(prepare_meshes(&scene).is_err());
    }

    #[test]
    fn decodes_raw_rgba_texture() {
        let rgba = vec![255u8, 0, 0, 255, 0, 255, 0, 255, 0, 0, 255, 255, 255, 255, 0, 255];
        let tex = decode_texture(&rgba, Some(2), Some(2), 0).unwrap();
        assert_eq!(tex.width, 2);
        assert_eq!(tex.height, 2);
        assert_eq!(tex.rgba.len(), 16);
    }
}
